/**
   * Professions.ts — Star-Wars-Galaxies-style profession trees.
   *
   * Source of truth: docs/inventory/professions.csv. The branch/skill arrays
   * below were generated from that CSV (see scripts/genProfessions if/when
   * regenerated). Do NOT edit individual skill entries by hand here without
   * also updating the CSV.
   *
   * 7 professions × 5 branches × 4 ranks + 1 Master per profession = 147
   * skills. Each profession earns its own XP from in-game activities (see
   * `ProfessionsService` for the runtime + persistence layer). Spending
   * profession XP unlocks skills which expose passive bonuses the engine
   * can read at runtime.
   *
   * Designed so it does NOT conflict with the existing 4-track PerksBook —
   * that system continues to spend `playerStats.skillPoints` from
   * level-ups; this system spends per-profession XP earned independently.
   */

  // ─── Profession identifiers ──────────────────────────────────────────────────

  export const PROFESSIONS = [
    'gathering',
    'hunting',
    'crafting',
    'township',
    'survival',
    'chemistry',
    'combat',
  ] as const;

  export type Profession = typeof PROFESSIONS[number];

  export interface ProfessionMeta {
    id: Profession;
    label: string;
    blurb: string;
    color: string;
    /** Hero icon shown on tab + summary. */
    icon: string;
  }

  export const PROFESSION_META: Record<Profession, ProfessionMeta> = {
  gathering: {
    id: "gathering",
    label: "Gathering",
    blurb: "Forestry, mining, salvage, permafrost, rift crystals — every node has a yield curve you can bend.",
    color: "#6ec96e",
    icon: "/icons/perks/maker/15.png",
  },
  hunting: {
    id: "hunting",
    label: "Hunting",
    blurb: "Fishing, beasts, bounty contracts, trail-craft, traps. The wild and what it leaves behind.",
    color: "#c5703a",
    icon: "/icons/perks/hero/5.png",
  },
  crafting: {
    id: "crafting",
    label: "Crafting",
    blurb: "Equipment, blades, guns, armour, tinkering. Turn raw ore into a reason to keep going.",
    color: "#c5a059",
    icon: "/icons/perks/warrior/15.png",
  },
  township: {
    id: "township",
    label: "Township",
    blurb: "Leadership, building, trade, diplomacy, defenses. A camp prosperous enough to outlast the rift.",
    color: "#d8a93a",
    icon: "/icons/perks/hero/26.png",
  },
  survival: {
    id: "survival",
    label: "Survival",
    blurb: "Combat training, resolve, endurance, biome lore, veterancy. The half-second between a knockdown and a kill.",
    color: "#5a9ad8",
    icon: "/icons/perks/smarts/24.png",
  },
  chemistry: {
    id: "chemistry",
    label: "Chemistry",
    blurb: "Cooking, potions, explosives, toxins, refining. Every brew, blast and meal that buys you another wave.",
    color: "#9a6ecf",
    icon: "/icons/perks/maker/45.png",
  },
  combat: {
    id: "combat",
    label: "Combat",
    blurb: "Pistols, rifles, blades, hammers, theft. The mastery profile of a working killer.",
    color: "#d05050",
    icon: "/icons/perks/warrior/55.png",
  },
};

  // ─── Effect keys (passives the engine reads) ─────────────────────────────────
  //
  // String-typed for forward compatibility with new CSV-driven keys. Engine
  // consumers (`ProfessionsService.getEffect('bountyXpBonus')`) keep the same
  // API; new keys can be added by editing the CSV alone.
  export type ProfessionEffectKey = string;
  export type ProfessionEffects = Record<ProfessionEffectKey, number>;

  // Boolean / string passives ("frostbiteImmunity true", "harvesterUnlocked
  // forager") are kept separately on each skill via `extras`. They are not
  // summed; the runtime can probe them via `hasFlag` / `getUnlock` below.
  export type ProfessionExtras = Record<string, boolean | string>;

  // ─── Skill definition ───────────────────────────────────────────────────────

  export interface ProfessionSkill {
    id: string;                          // unique across all professions
    prof: Profession;
    branch: string;                      // branch slug, or 'master'
    rank: 1 | 2 | 3 | 4 | 'M';
    name: string;
    desc: string;
    /** XP cost in the OWNING profession to learn this skill. */
    cost: number;
    /** Other skill ids the player must already own. */
    prereq: string[];
    /** Resolved icon URL. */
    icon: string;
    /** Signature item that thematically pairs with the skill (display only). */
    signature: string;
    /** Recipe ids granted on learn (display only — engine picks them up via id). */
    recipes: string[];
    /** Numeric passives summed by `aggregatePassives`. */
    passive: ProfessionEffects;
    /** Boolean / string passives (flags, unlocks) — not summed. */
    extras: ProfessionExtras;
  }

  export type ProfessionMaster = ProfessionSkill & { rank: 'M' };

  export interface ProfessionBranch {
    id: string;
    prof: Profession;
    label: string;
    skills: ProfessionSkill[];
  }

  // ─── Branch + master data, generated from professions.csv ───────────────────

const BR_GATHERING_FORESTRY: ProfessionBranch = {
  id: "forestry",
  prof: "gathering",
  label: "Forestry",
  skills: [
  {
      id: "gathering.forestry.1",
      prof: "gathering",
      branch: "forestry",
      rank: 1,
      name: "Practiced Hand",
      desc: "+10% timber and branch yield from felled trees.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/maker/11.png",
      signature: "Hatchet",
      recipes: [],
      passive: { "harvestYieldBonus": 0.1 },
      extras: {},
    },
  {
      id: "gathering.forestry.2",
      prof: "gathering",
      branch: "forestry",
      rank: 2,
      name: "Eye for Saplings",
      desc: "+20% chance for rare wood (oak_dark / sappling_pine); unlocks Forager hire (passive berry/herb gather in camp radius).",
      cost: 2,
      prereq: ["gathering.forestry.1"],
      icon: "/icons/perks/maker/12.png",
      signature: "Hatchet",
      recipes: ["hire_forager"],
      passive: { "harvestRareBonus": 0.2 },
      extras: { "harvesterUnlocked": "forager" },
    },
  {
      id: "gathering.forestry.3",
      prof: "gathering",
      branch: "forestry",
      rank: 3,
      name: "Coppice Tender",
      desc: "Felled trees regrow 2× faster on the same tile.",
      cost: 4,
      prereq: ["gathering.forestry.2"],
      icon: "/icons/perks/maker/13.png",
      signature: "Hatchet",
      recipes: ["craft_planter_box"],
      passive: { "treeRegrowSpeedBonus": 1 },
      extras: {},
    },
  {
      id: "gathering.forestry.4",
      prof: "gathering",
      branch: "forestry",
      rank: 4,
      name: "Moonleaf Druid",
      desc: "+25% herb_rare drops, herbs glow within 30m at night.",
      cost: 8,
      prereq: ["gathering.forestry.3"],
      icon: "/icons/perks/maker/14.png",
      signature: "Hatchet / Druid's Sickle",
      recipes: ["craft_moonleaf_satchel"],
      passive: { "harvestRareBonus": 0.25, "nightHerbVisionRange": 30 },
      extras: {},
    },
  ],
};

const BR_GATHERING_MINING: ProfessionBranch = {
  id: "mining",
  prof: "gathering",
  label: "Mining",
  skills: [
  {
      id: "gathering.mining.1",
      prof: "gathering",
      branch: "mining",
      rank: 1,
      name: "Steady Swing",
      desc: "-10% time between mining hits.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/maker/15.png",
      signature: "Pickaxe",
      recipes: [],
      passive: { "harvestSpeedBonus": 0.1 },
      extras: {},
    },
  {
      id: "gathering.mining.2",
      prof: "gathering",
      branch: "mining",
      rank: 2,
      name: "Ironvein",
      desc: "+15% iron and stone yield.",
      cost: 2,
      prereq: ["gathering.mining.1"],
      icon: "/icons/perks/maker/16.png",
      signature: "Pickaxe",
      recipes: [],
      passive: { "harvestYieldBonus": 0.15, "ironYieldBonus": 0.15 },
      extras: {},
    },
  {
      id: "gathering.mining.3",
      prof: "gathering",
      branch: "mining",
      rank: 3,
      name: "Coppervein",
      desc: "+20% copper, +15% flint and stone (stacks).",
      cost: 4,
      prereq: ["gathering.mining.2"],
      icon: "/icons/perks/maker/17.png",
      signature: "Pickaxe",
      recipes: [],
      passive: { "copperYieldBonus": 0.2, "harvestYieldBonus": 0.15 },
      extras: {},
    },
  {
      id: "gathering.mining.4",
      prof: "gathering",
      branch: "mining",
      rank: 4,
      name: "Deepcore Sapper",
      desc: "+25% all metals, veins yield 2× when struck with rank-3+ pickaxe.",
      cost: 8,
      prereq: ["gathering.mining.3"],
      icon: "/icons/perks/maker/18.png",
      signature: "Pickaxe / Steel Pickaxe",
      recipes: ["craft_pickaxe_steel"],
      passive: { "harvestYieldBonus": 0.25, "veinDoubleYieldChance": 0.5 },
      extras: {},
    },
  ],
};

const BR_GATHERING_PERMAFROST: ProfessionBranch = {
  id: "permafrost",
  prof: "gathering",
  label: "Permafrost",
  skills: [
  {
      id: "gathering.permafrost.1",
      prof: "gathering",
      branch: "permafrost",
      rank: 1,
      name: "Cold Hands",
      desc: "Frostbite immunity in tundra biome.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/maker/19.png",
      signature: "Ice Pickaxe",
      recipes: [],
      passive: {},
      extras: { "frostbiteImmunity": true },
    },
  {
      id: "gathering.permafrost.2",
      prof: "gathering",
      branch: "permafrost",
      rank: 2,
      name: "Glacial Reader",
      desc: "Permafrost veins ping the minimap within 50m.",
      cost: 2,
      prereq: ["gathering.permafrost.1"],
      icon: "/icons/perks/maker/20.png",
      signature: "Ice Pickaxe",
      recipes: [],
      passive: { "permafrostMinimapRange": 50 },
      extras: {},
    },
  {
      id: "gathering.permafrost.3",
      prof: "gathering",
      branch: "permafrost",
      rank: 3,
      name: "Ice Whisperer",
      desc: "+25% permafrost ore + tundra herb yield.",
      cost: 4,
      prereq: ["gathering.permafrost.2"],
      icon: "/icons/perks/maker/21.png",
      signature: "Ice Pickaxe",
      recipes: ["craft_ice_pickaxe"],
      passive: { "permafrostYieldBonus": 0.25, "harvestRareBonus": 0.1 },
      extras: {},
    },
  {
      id: "gathering.permafrost.4",
      prof: "gathering",
      branch: "permafrost",
      rank: 4,
      name: "Aurora Forager",
      desc: "+30% all tundra resources, unlocks aurora_crystal harvest.",
      cost: 8,
      prereq: ["gathering.permafrost.3"],
      icon: "/icons/perks/maker/22.png",
      signature: "Ice Pickaxe / Glacial Drill",
      recipes: ["craft_aurora_lantern"],
      passive: { "permafrostYieldBonus": 0.3 },
      extras: { "auroraCrystalUnlocked": true },
    },
  ],
};

const BR_GATHERING_CRYSTALS: ProfessionBranch = {
  id: "crystals",
  prof: "gathering",
  label: "Rift Crystals",
  skills: [
  {
      id: "gathering.crystals.1",
      prof: "gathering",
      branch: "crystals",
      rank: 1,
      name: "Resonance",
      desc: "crystal_x veins audibly hum within 30m.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/maker/23.png",
      signature: "Crystal Resonator",
      recipes: [],
      passive: { "crystalDetectRange": 30 },
      extras: {},
    },
  {
      id: "gathering.crystals.2",
      prof: "gathering",
      branch: "crystals",
      rank: 2,
      name: "Refraction",
      desc: "+15% crystal yield.",
      cost: 2,
      prereq: ["gathering.crystals.1"],
      icon: "/icons/perks/maker/24.png",
      signature: "Crystal Resonator",
      recipes: ["craft_resonator_basic"],
      passive: { "crystalYieldBonus": 0.15 },
      extras: {},
    },
  {
      id: "gathering.crystals.3",
      prof: "gathering",
      branch: "crystals",
      rank: 3,
      name: "Shard Binder",
      desc: "Unlocks rift_shard harvest from rift anomalies.",
      cost: 4,
      prereq: ["gathering.crystals.2"],
      icon: "/icons/perks/maker/25.png",
      signature: "Crystal Resonator",
      recipes: ["craft_shard_focus"],
      passive: { "crystalYieldBonus": 0.1 },
      extras: { "riftShardUnlocked": true },
    },
  {
      id: "gathering.crystals.4",
      prof: "gathering",
      branch: "crystals",
      rank: 4,
      name: "Riftcaller",
      desc: "+50% crystal yield, anomalies grant +1 rift_shard each.",
      cost: 8,
      prereq: ["gathering.crystals.3"],
      icon: "/icons/perks/maker/26.png",
      signature: "Crystal Resonator / Attuned Resonator",
      recipes: ["craft_resonator_attuned"],
      passive: { "crystalYieldBonus": 0.5, "anomalyShardBonus": 1 },
      extras: {},
    },
  ],
};

const BR_GATHERING_SALVAGE: ProfessionBranch = {
  id: "salvage",
  prof: "gathering",
  label: "Salvage",
  skills: [
  {
      id: "gathering.salvage.1",
      prof: "gathering",
      branch: "salvage",
      rank: 1,
      name: "Scrap Magnet",
      desc: "+20% scrap from ruined chests and wrecks.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/maker/27.png",
      signature: "Scrap Cutter",
      recipes: [],
      passive: { "salvageYieldBonus": 0.2 },
      extras: {},
    },
  {
      id: "gathering.salvage.2",
      prof: "gathering",
      branch: "salvage",
      rank: 2,
      name: "Field Stripper",
      desc: "Derelict tech grants 2× component drops.",
      cost: 2,
      prereq: ["gathering.salvage.1"],
      icon: "/icons/perks/maker/28.png",
      signature: "Scrap Cutter / Multitool",
      recipes: ["craft_multitool"],
      passive: { "derelictDoubleDropChance": 1 },
      extras: {},
    },
  {
      id: "gathering.salvage.3",
      prof: "gathering",
      branch: "salvage",
      rank: 3,
      name: "Junker",
      desc: "Unlocks weapon → component recycling at workbench.",
      cost: 4,
      prereq: ["gathering.salvage.2"],
      icon: "/icons/perks/maker/29.png",
      signature: "Scrap Cutter / Multitool",
      recipes: ["craft_recycle_blade", "craft_recycle_gun"],
      passive: {},
      extras: { "recyclingUnlocked": true },
    },
  {
      id: "gathering.salvage.4",
      prof: "gathering",
      branch: "salvage",
      rank: 4,
      name: "Wreck Diver",
      desc: "+50% rare salvage, sunken wrecks become harvestable.",
      cost: 8,
      prereq: ["gathering.salvage.3"],
      icon: "/icons/perks/maker/30.png",
      signature: "Scrap Cutter / Rebreather",
      recipes: ["craft_dive_rebreather"],
      passive: { "salvageYieldBonus": 0.5 },
      extras: { "sunkenWreckUnlocked": true },
    },
  ],
};

const MASTER_GATHERING: ProfessionMaster = {
      id: "gathering.master",
      prof: "gathering",
      branch: "master",
      rank: "M",
      name: "Land's Bounty",
      desc: "PROFESSION MASTER — +25% all yield, +25% rare drops, +15% speed, all branch unlocks active. Requires Forestry 4 + Mining 4 + Permafrost 4 + Crystals 4 + Salvage 4.",
      cost: 20,
      prereq: ["gathering.forestry.4", "gathering.mining.4", "gathering.permafrost.4", "gathering.crystals.4", "gathering.salvage.4"],
      icon: "/icons/perks/maker/31.png",
      signature: "Land-Steward's Crook",
      recipes: ["craft_resonator_master", "craft_dredge_rig"],
      passive: { "harvestYieldBonus": 0.25, "harvestRareBonus": 0.25, "harvestSpeedBonus": 0.15 },
      extras: {},
    };

const BR_HUNTING_FISHING: ProfessionBranch = {
  id: "fishing",
  prof: "hunting",
  label: "Fishing",
  skills: [
  {
      id: "hunting.fishing.1",
      prof: "hunting",
      branch: "fishing",
      rank: 1,
      name: "Patient Line",
      desc: "+10% fish per pond.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/hero/1.png",
      signature: "Fishing Rod",
      recipes: ["craft_fishing_rod"],
      passive: { "fishingYieldBonus": 0.1 },
      extras: {},
    },
  {
      id: "hunting.fishing.2",
      prof: "hunting",
      branch: "fishing",
      rank: 2,
      name: "Tide Reader",
      desc: "+15% rare catches in any pond.",
      cost: 2,
      prereq: ["hunting.fishing.1"],
      icon: "/icons/perks/hero/2.png",
      signature: "Fishing Rod",
      recipes: ["craft_bait_worm"],
      passive: { "harvestRareBonus": 0.15 },
      extras: {},
    },
  {
      id: "hunting.fishing.3",
      prof: "hunting",
      branch: "fishing",
      rank: 3,
      name: "Net Weaver",
      desc: "+20% fish (stacks).",
      cost: 4,
      prereq: ["hunting.fishing.2"],
      icon: "/icons/perks/hero/3.png",
      signature: "Fishing Rod",
      recipes: ["craft_fishing_net"],
      passive: { "fishingYieldBonus": 0.2 },
      extras: {},
    },
  {
      id: "hunting.fishing.4",
      prof: "hunting",
      branch: "fishing",
      rank: 4,
      name: "Leviathan Lure",
      desc: "+30% first cast yield, unlocks leviathan-class catches.",
      cost: 8,
      prereq: ["hunting.fishing.3"],
      icon: "/icons/perks/hero/4.png",
      signature: "Fishing Rod / Harpoon",
      recipes: ["craft_harpoon", "craft_deepsea_net", "craft_leviathan_bait"],
      passive: { "fishingYieldBonus": 0.3 },
      extras: { "leviathanUnlocked": true },
    },
  ],
};

const BR_HUNTING_ANIMALS: ProfessionBranch = {
  id: "animals",
  prof: "hunting",
  label: "Animals",
  skills: [
  {
      id: "hunting.animals.1",
      prof: "hunting",
      branch: "animals",
      rank: 1,
      name: "Marksman's Eye",
      desc: "+10% Hunting XP per animal kill.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/hero/5.png",
      signature: "Bow / Skinning Knife",
      recipes: ["craft_skinning_knife"],
      passive: { "bountyXpBonus": 0.1 },
      extras: {},
    },
  {
      id: "hunting.animals.2",
      prof: "hunting",
      branch: "animals",
      rank: 2,
      name: "Stalker",
      desc: "+5% damage to elite beasts.",
      cost: 2,
      prereq: ["hunting.animals.1"],
      icon: "/icons/perks/hero/6.png",
      signature: "Bow / Skinning Knife",
      recipes: ["craft_snare_trap"],
      passive: { "gunsmithDamageBonus": 0.05 },
      extras: {},
    },
  {
      id: "hunting.animals.3",
      prof: "hunting",
      branch: "animals",
      rank: 3,
      name: "Trophy Carver",
      desc: "+15% leather/skin from animal kills.",
      cost: 4,
      prereq: ["hunting.animals.2"],
      icon: "/icons/perks/hero/7.png",
      signature: "Bow / Skinning Knife",
      recipes: ["craft_bear_trap", "craft_taxidermy_kit"],
      passive: { "skinningYieldBonus": 0.15 },
      extras: {},
    },
  {
      id: "hunting.animals.4",
      prof: "hunting",
      branch: "animals",
      rank: 4,
      name: "Big Game Hunter",
      desc: "+25% Hunting XP from boss beasts, +10% damage to all wildlife.",
      cost: 8,
      prereq: ["hunting.animals.3"],
      icon: "/icons/perks/hero/8.png",
      signature: "Bow / Sniper Rifle",
      recipes: ["craft_tracking_arrow", "craft_trophy_mount"],
      passive: { "bountyXpBonus": 0.25, "gunsmithDamageBonus": 0.1 },
      extras: {},
    },
  ],
};

const BR_HUNTING_BOUNTY: ProfessionBranch = {
  id: "bounty",
  prof: "hunting",
  label: "Bounty (Missions)",
  skills: [
  {
      id: "hunting.bounty.1",
      prof: "hunting",
      branch: "bounty",
      rank: 1,
      name: "Bounty Board Initiate",
      desc: "+1 active bounty contract slot. Unlocks animal contracts.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/hero/9.png",
      signature: "Wanted Poster / Manacles",
      recipes: ["craft_bounty_poster"],
      passive: { "bountyContractSlots": 1 },
      extras: {},
    },
  {
      id: "hunting.bounty.2",
      prof: "hunting",
      branch: "bounty",
      rank: 2,
      name: "Tracker's Token",
      desc: "+25% bounty mission gold reward.",
      cost: 2,
      prereq: ["hunting.bounty.1"],
      icon: "/icons/perks/hero/10.png",
      signature: "Wanted Poster / Manacles",
      recipes: ["craft_wanted_dossier"],
      passive: { "bountyGoldBonus": 0.25 },
      extras: {},
    },
  {
      id: "hunting.bounty.3",
      prof: "hunting",
      branch: "bounty",
      rank: 3,
      name: "Veteran Bounty",
      desc: "+1 active bounty slot (stacks), +10% bounty mission XP.",
      cost: 4,
      prereq: ["hunting.bounty.2"],
      icon: "/icons/perks/hero/11.png",
      signature: "Wanted Poster / Manacles",
      recipes: ["craft_capture_net", "craft_bounty_lockbox"],
      passive: { "bountyContractSlots": 1, "bountyMissionXpBonus": 0.1 },
      extras: {},
    },
  {
      id: "hunting.bounty.4",
      prof: "hunting",
      branch: "bounty",
      rank: 4,
      name: "Bounty King",
      desc: "+50% rare contract chance, +25% bounty mission XP. Unlocks villain NPC contracts.",
      cost: 8,
      prereq: ["hunting.bounty.3"],
      icon: "/icons/perks/hero/12.png",
      signature: "Wanted Poster / Manacles",
      recipes: ["craft_villain_trophy", "craft_manacles"],
      passive: { "bountyRareContractBonus": 0.5, "bountyMissionXpBonus": 0.25 },
      extras: { "villainContractsUnlocked": true },
    },
  ],
};

const BR_HUNTING_TRACKING: ProfessionBranch = {
  id: "tracking",
  prof: "hunting",
  label: "Tracking",
  skills: [
  {
      id: "hunting.tracking.1",
      prof: "hunting",
      branch: "tracking",
      rank: 1,
      name: "Sharp Senses",
      desc: "Enemies appear on minimap within 25m.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/hero/13.png",
      signature: "Spyglass",
      recipes: [],
      passive: { "minimapEnemyRange": 25 },
      extras: {},
    },
  {
      id: "hunting.tracking.2",
      prof: "hunting",
      branch: "tracking",
      rank: 2,
      name: "Bloodtrail",
      desc: "Wounded beasts leave visible blood trails for 60s.",
      cost: 2,
      prereq: ["hunting.tracking.1"],
      icon: "/icons/perks/hero/14.png",
      signature: "Spyglass",
      recipes: ["craft_spyglass"],
      passive: { "bloodTrailDuration": 60 },
      extras: {},
    },
  {
      id: "hunting.tracking.3",
      prof: "hunting",
      branch: "tracking",
      rank: 3,
      name: "Bird's Eye",
      desc: "+50% spyglass zoom range; spot rare nodes at distance.",
      cost: 4,
      prereq: ["hunting.tracking.2"],
      icon: "/icons/perks/hero/15.png",
      signature: "Spyglass / Brass Compass",
      recipes: ["craft_compass_brass"],
      passive: { "spyglassZoomBonus": 0.5 },
      extras: { "rareNodeMarker": true },
    },
  {
      id: "hunting.tracking.4",
      prof: "hunting",
      branch: "tracking",
      rank: 4,
      name: "Pathfinder",
      desc: "Reveals map fog within 100m as you move; +25% out-of-combat speed.",
      cost: 8,
      prereq: ["hunting.tracking.3"],
      icon: "/icons/perks/hero/16.png",
      signature: "Spyglass / Pathfinder's Cloak",
      recipes: ["craft_pathfinders_cloak"],
      passive: { "fogRevealRange": 100, "oocSpeedBonus": 0.25 },
      extras: {},
    },
  ],
};

const BR_HUNTING_TRAPPING: ProfessionBranch = {
  id: "trapping",
  prof: "hunting",
  label: "Trapping",
  skills: [
  {
      id: "hunting.trapping.1",
      prof: "hunting",
      branch: "trapping",
      rank: 1,
      name: "Snare Master",
      desc: "Placed traps trigger 2× more often.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/hero/17.png",
      signature: "Snare Kit",
      recipes: [],
      passive: { "trapTriggerBonus": 1 },
      extras: {},
    },
  {
      id: "hunting.trapping.2",
      prof: "hunting",
      branch: "trapping",
      rank: 2,
      name: "Passive Hunter",
      desc: "Set traps grant +5 Hunting XP every 5 minutes (max 6/h).",
      cost: 2,
      prereq: ["hunting.trapping.1"],
      icon: "/icons/perks/hero/18.png",
      signature: "Snare Kit",
      recipes: ["craft_snare_advanced"],
      passive: { "passiveTrapXpRate": 1 },
      extras: {},
    },
  {
      id: "hunting.trapping.3",
      prof: "hunting",
      branch: "trapping",
      rank: 3,
      name: "Lure Crafter",
      desc: "bait_worm and bait_meat last 2× longer in traps; unlocks Trapper hire (resets snares & gathers carcasses).",
      cost: 4,
      prereq: ["hunting.trapping.2"],
      icon: "/icons/perks/hero/19.png",
      signature: "Snare Kit",
      recipes: ["craft_bait_meat", "craft_bait_lure_pheromone", "hire_trapper"],
      passive: { "baitDurationBonus": 1 },
      extras: { "allyUnlocked": "trapper" },
    },
  {
      id: "hunting.trapping.4",
      prof: "hunting",
      branch: "trapping",
      rank: 4,
      name: "Honey Pot",
      desc: "Unlock honey_pot trap (catches rare beasts overnight), +50% trap rare drop chance.",
      cost: 8,
      prereq: ["hunting.trapping.3"],
      icon: "/icons/perks/hero/20.png",
      signature: "Snare Kit",
      recipes: ["craft_honey_pot"],
      passive: { "trapRareDropBonus": 0.5 },
      extras: { "honeyPotUnlocked": true },
    },
  ],
};

const MASTER_HUNTING: ProfessionMaster = {
      id: "hunting.master",
      prof: "hunting",
      branch: "master",
      rank: "M",
      name: "Apex Predator",
      desc: "PROFESSION MASTER — +25% all damage, +25% hunt XP, +25% skinning, +1 contract slot, all unlocks active. Requires Fishing 4 + Animals 4 + Bounty 4 + Tracking 4 + Trapping 4.",
      cost: 20,
      prereq: ["hunting.fishing.4", "hunting.animals.4", "hunting.bounty.4", "hunting.tracking.4", "hunting.trapping.4"],
      icon: "/icons/perks/hero/21.png",
      signature: "Bow / Sniper Rifle",
      recipes: ["craft_legendary_trophy"],
      passive: { "gunsmithDamageBonus": 0.25, "bladesmithDamageBonus": 0.25, "bountyXpBonus": 0.25, "skinningYieldBonus": 0.25, "bountyContractSlots": 1 },
      extras: {},
    };

const BR_CRAFTING_EQUIPMENT: ProfessionBranch = {
  id: "equipment",
  prof: "crafting",
  label: "Equipment",
  skills: [
  {
      id: "crafting.equipment.1",
      prof: "crafting",
      branch: "equipment",
      rank: 1,
      name: "Apprentice Smith",
      desc: "-10% material cost on craft.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/warrior/1.png",
      signature: "Carpenter Hammer",
      recipes: ["craft_pickaxe", "craft_hammer_tool", "craft_bucket_metal"],
      passive: { "craftCostReduction": 0.1 },
      extras: {},
    },
  {
      id: "crafting.equipment.2",
      prof: "crafting",
      branch: "equipment",
      rank: 2,
      name: "Field Repair",
      desc: "+10% craft quality.",
      cost: 2,
      prereq: ["crafting.equipment.1"],
      icon: "/icons/perks/warrior/2.png",
      signature: "Carpenter Hammer",
      recipes: ["craft_repair_kit", "craft_whetstone", "craft_torch_metal"],
      passive: { "craftQualityBonus": 0.1 },
      extras: {},
    },
  {
      id: "crafting.equipment.3",
      prof: "crafting",
      branch: "equipment",
      rank: 3,
      name: "Layered Plate",
      desc: "+10% armour defense.",
      cost: 4,
      prereq: ["crafting.equipment.2"],
      icon: "/icons/perks/warrior/3.png",
      signature: "Carpenter Hammer",
      recipes: ["craft_shield_round", "craft_shield_round_2"],
      passive: { "armourDefenseBonus": 0.1 },
      extras: {},
    },
  {
      id: "crafting.equipment.4",
      prof: "crafting",
      branch: "equipment",
      rank: 4,
      name: "Artificer",
      desc: "-15% cost, +25% quality on legendary recipes (stacks).",
      cost: 8,
      prereq: ["crafting.equipment.3"],
      icon: "/icons/perks/warrior/4.png",
      signature: "Carpenter Hammer",
      recipes: ["craft_workbench", "craft_anvil", "craft_weapon_stand", "craft_workbench_drawers"],
      passive: { "craftCostReduction": 0.15, "craftQualityBonus": 0.25 },
      extras: {},
    },
  ],
};

const BR_CRAFTING_BLADESMITH: ProfessionBranch = {
  id: "bladesmith",
  prof: "crafting",
  label: "Bladesmith",
  skills: [
  {
      id: "crafting.bladesmith.1",
      prof: "crafting",
      branch: "bladesmith",
      rank: 1,
      name: "Sharper Edge",
      desc: "+5% melee weapon damage.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/warrior/11.png",
      signature: "Smith's Hammer",
      recipes: ["craft_dagger", "craft_iron_sword"],
      passive: { "bladesmithDamageBonus": 0.05 },
      extras: {},
    },
  {
      id: "crafting.bladesmith.2",
      prof: "crafting",
      branch: "bladesmith",
      rank: 2,
      name: "Folded Steel",
      desc: "+10% melee weapon damage (stacks).",
      cost: 2,
      prereq: ["crafting.bladesmith.1"],
      icon: "/icons/perks/warrior/12.png",
      signature: "Smith's Hammer",
      recipes: ["craft_sword_2", "craft_dagger_2", "craft_axe_small"],
      passive: { "bladesmithDamageBonus": 0.1 },
      extras: {},
    },
  {
      id: "crafting.bladesmith.3",
      prof: "crafting",
      branch: "bladesmith",
      rank: 3,
      name: "Warden's Blade",
      desc: "+10% craft quality on swords.",
      cost: 4,
      prereq: ["crafting.bladesmith.2"],
      icon: "/icons/perks/warrior/13.png",
      signature: "Smith's Hammer",
      recipes: ["craft_axe", "craft_hammer_small", "craft_spear"],
      passive: { "craftQualityBonus": 0.1 },
      extras: {},
    },
  {
      id: "crafting.bladesmith.4",
      prof: "crafting",
      branch: "bladesmith",
      rank: 4,
      name: "Soulforged",
      desc: "+25% bladed damage, +15% melee crit (stacks).",
      cost: 8,
      prereq: ["crafting.bladesmith.3"],
      icon: "/icons/perks/warrior/14.png",
      signature: "Smith's Hammer",
      recipes: ["craft_sword_big", "craft_axe_double", "craft_hammer_double", "craft_claymore", "craft_scythe"],
      passive: { "bladesmithDamageBonus": 0.15 },
      extras: {},
    },
  ],
};

const BR_CRAFTING_GUNSMITH: ProfessionBranch = {
  id: "gunsmith",
  prof: "crafting",
  label: "Gunsmith",
  skills: [
  {
      id: "crafting.gunsmith.1",
      prof: "crafting",
      branch: "gunsmith",
      rank: 1,
      name: "True Sights",
      desc: "+5% ranged weapon damage.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/warrior/21.png",
      signature: "Gunsmith Calipers",
      recipes: ["craft_bow_wooden", "craft_arrow_iron", "craft_pistol_1"],
      passive: { "gunsmithDamageBonus": 0.05 },
      extras: {},
    },
  {
      id: "crafting.gunsmith.2",
      prof: "crafting",
      branch: "gunsmith",
      rank: 2,
      name: "Tight Bore",
      desc: "+10% ranged damage (stacks).",
      cost: 2,
      prereq: ["crafting.gunsmith.1"],
      icon: "/icons/perks/warrior/22.png",
      signature: "Gunsmith Calipers",
      recipes: ["craft_bow_wooden_2", "craft_pistol_2", "craft_pistol_3", "craft_revolver_1", "craft_smg_1"],
      passive: { "gunsmithDamageBonus": 0.1 },
      extras: {},
    },
  {
      id: "crafting.gunsmith.3",
      prof: "crafting",
      branch: "gunsmith",
      rank: 3,
      name: "Quick Draw",
      desc: "-10% ranged crafting cost.",
      cost: 4,
      prereq: ["crafting.gunsmith.2"],
      icon: "/icons/perks/warrior/23.png",
      signature: "Gunsmith Calipers",
      recipes: ["craft_smg_2", "craft_smg_3", "craft_shotgun_1", "craft_shotgun_2", "craft_bow_evil"],
      passive: { "craftCostReduction": 0.1 },
      extras: {},
    },
  {
      id: "crafting.gunsmith.4",
      prof: "crafting",
      branch: "gunsmith",
      rank: 4,
      name: "Rift-Hunter Rifle",
      desc: "+25% ranged damage, +15% boss damage (stacks).",
      cost: 8,
      prereq: ["crafting.gunsmith.3"],
      icon: "/icons/perks/warrior/24.png",
      signature: "Gunsmith Calipers",
      recipes: ["craft_assault_rifle_1", "craft_assault_rifle_2", "craft_assault_rifle_3", "craft_shotgun_sawedoff", "craft_shotgun_3", "craft_bullpup_1", "craft_sniper_1", "craft_sniper_5", "craft_assault_rifle2_4", "craft_bullpup_3"],
      passive: { "gunsmithDamageBonus": 0.15 },
      extras: {},
    },
  ],
};

const BR_CRAFTING_ARMOUR: ProfessionBranch = {
  id: "armour",
  prof: "crafting",
  label: "Armour",
  skills: [
  {
      id: "crafting.armour.1",
      prof: "crafting",
      branch: "armour",
      rank: 1,
      name: "Padded Lining",
      desc: "+5% armour defense.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/hero/22.png",
      signature: "Plate Hammer",
      recipes: ["craft_armour_peasant_chest", "craft_armour_peasant_legs", "craft_armour_peasant_feet", "craft_armour_peasant_arms"],
      passive: { "armourDefenseBonus": 0.05 },
      extras: {},
    },
  {
      id: "crafting.armour.2",
      prof: "crafting",
      branch: "armour",
      rank: 2,
      name: "Plate & Mail",
      desc: "+10% defense (stacks).",
      cost: 2,
      prereq: ["crafting.armour.1"],
      icon: "/icons/perks/hero/23.png",
      signature: "Plate Hammer",
      recipes: ["craft_armour_leather_set", "craft_helmet_open"],
      passive: { "armourDefenseBonus": 0.1 },
      extras: {},
    },
  {
      id: "crafting.armour.3",
      prof: "crafting",
      branch: "armour",
      rank: 3,
      name: "Reinforced Joints",
      desc: "+10% damage reduction.",
      cost: 4,
      prereq: ["crafting.armour.2"],
      icon: "/icons/perks/hero/24.png",
      signature: "Plate Hammer",
      recipes: ["craft_armour_mail_set", "craft_shield_heater"],
      passive: { "damageReductionBonus": 0.1 },
      extras: {},
    },
  {
      id: "crafting.armour.4",
      prof: "crafting",
      branch: "armour",
      rank: 4,
      name: "Aegis Plating",
      desc: "+25% damage reduction, +15% defense (stacks).",
      cost: 8,
      prereq: ["crafting.armour.3"],
      icon: "/icons/perks/hero/25.png",
      signature: "Plate Hammer",
      recipes: ["craft_armour_plate_set", "craft_shield_heater_2", "craft_helmet_full", "craft_armour_ranger_chest", "craft_armour_ranger_legs", "craft_armour_ranger_feet", "craft_armour_ranger_arms", "craft_armour_ranger_head", "craft_armour_ranger_shoulders"],
      passive: { "damageReductionBonus": 0.25, "armourDefenseBonus": 0.15 },
      extras: {},
    },
  ],
};

const BR_CRAFTING_TINKERING: ProfessionBranch = {
  id: "tinkering",
  prof: "crafting",
  label: "Tinkering",
  skills: [
  {
      id: "crafting.tinkering.1",
      prof: "crafting",
      branch: "tinkering",
      rank: 1,
      name: "Mod Slot",
      desc: "First weapon attachment per gun costs no schematic.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/smarts/1.png",
      signature: "Soldering Iron",
      recipes: ["craft_attach_silencer_1", "craft_attach_scope_1"],
      passive: {},
      extras: { "firstAttachmentFree": true },
    },
  {
      id: "crafting.tinkering.2",
      prof: "crafting",
      branch: "tinkering",
      rank: 2,
      name: "Hot Wire",
      desc: "Unlocks mid-tier attachment recipes; +10% gadget effect.",
      cost: 2,
      prereq: ["crafting.tinkering.1"],
      icon: "/icons/perks/smarts/2.png",
      signature: "Soldering Iron",
      recipes: ["craft_attach_silencer_2", "craft_attach_scope_2", "craft_attach_grip"],
      passive: { "gadgetEffectBonus": 0.1 },
      extras: {},
    },
  {
      id: "crafting.tinkering.3",
      prof: "crafting",
      branch: "tinkering",
      rank: 3,
      name: "Engineer",
      desc: "Gadget cooldowns -20%; unlock heavy attachments.",
      cost: 4,
      prereq: ["crafting.tinkering.2"],
      icon: "/icons/perks/smarts/3.png",
      signature: "Soldering Iron / Multitool",
      recipes: ["craft_attach_bipod", "craft_attach_silencer_long", "craft_attach_scope_3", "craft_attach_tripod"],
      passive: { "gadgetCooldownReduction": 0.2, "gadgetEffectBonus": 0.1 },
      extras: {},
    },
  {
      id: "crafting.tinkering.4",
      prof: "crafting",
      branch: "tinkering",
      rank: 4,
      name: "Master Tinkerer",
      desc: "Gadgets crit for +50% effect; unlock prototype gadgets.",
      cost: 8,
      prereq: ["crafting.tinkering.3"],
      icon: "/icons/perks/smarts/4.png",
      signature: "Soldering Iron / Prototype Rig",
      recipes: ["craft_drone_recon", "craft_emp_grenade", "craft_grappling_hook"],
      passive: { "gadgetCritChance": 0.25, "gadgetCritBonus": 0.5 },
      extras: {},
    },
  ],
};

const MASTER_CRAFTING: ProfessionMaster = {
      id: "crafting.master",
      prof: "crafting",
      branch: "master",
      rank: "M",
      name: "Riftforge Artisan",
      desc: "PROFESSION MASTER — +15% all weapon damage, +25% craft quality, -15% craft cost, all unlocks active. Requires Equipment 4 + Bladesmith 4 + Gunsmith 4 + Armour 4 + Tinkering 4.",
      cost: 20,
      prereq: ["crafting.equipment.4", "crafting.bladesmith.4", "crafting.gunsmith.4", "crafting.armour.4", "crafting.tinkering.4"],
      icon: "/icons/perks/warrior/29.png",
      signature: "Anvil",
      recipes: ["craft_shield_celtic_golden", "craft_sword_golden", "craft_bow_golden", "craft_sniper_6", "craft_gun_scifi_pistol"],
      passive: { "bladesmithDamageBonus": 0.15, "gunsmithDamageBonus": 0.15, "armourDefenseBonus": 0.15, "craftQualityBonus": 0.25, "craftCostReduction": 0.15 },
      extras: {},
    };

const BR_TOWNSHIP_LEADERSHIP: ProfessionBranch = {
  id: "leadership",
  prof: "township",
  label: "Leadership",
  skills: [
  {
      id: "township.leadership.1",
      prof: "township",
      branch: "leadership",
      rank: 1,
      name: "Fair Hand",
      desc: "+1 NPC recruit cap.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/hero/26.png",
      signature: "Captain's Banner",
      recipes: [],
      passive: { "recruitCapBonus": 1 },
      extras: {},
    },
  {
      id: "township.leadership.2",
      prof: "township",
      branch: "leadership",
      rank: 2,
      name: "Camp Morale",
      desc: "+10% camp morale; +1 party Follower slot (hire_mercenary).",
      cost: 2,
      prereq: ["township.leadership.1"],
      icon: "/icons/perks/hero/27.png",
      signature: "Captain's Banner",
      recipes: ["build_banner", "hire_mercenary"],
      passive: { "campMoraleBonus": 0.1, "followerSlots": 1 },
      extras: {},
    },
  {
      id: "township.leadership.3",
      prof: "township",
      branch: "leadership",
      rank: 3,
      name: "Trusted Captain",
      desc: "+2 NPC recruit cap (stacks).",
      cost: 4,
      prereq: ["township.leadership.2"],
      icon: "/icons/perks/hero/28.png",
      signature: "Captain's Banner",
      recipes: ["build_recruit_post"],
      passive: { "recruitCapBonus": 2 },
      extras: {},
    },
  {
      id: "township.leadership.4",
      prof: "township",
      branch: "leadership",
      rank: 4,
      name: "Warlord",
      desc: "+5 NPC recruit cap, +20% morale, +2 party Follower slots (stacks).",
      cost: 8,
      prereq: ["township.leadership.3"],
      icon: "/icons/perks/hero/29.png",
      signature: "Captain's Banner / War Banner",
      recipes: ["build_banner_2", "build_war_banner"],
      passive: { "recruitCapBonus": 5, "campMoraleBonus": 0.2, "followerSlots": 2 },
      extras: {},
    },
  ],
};

const BR_TOWNSHIP_BUILDINGS: ProfessionBranch = {
  id: "buildings",
  prof: "township",
  label: "Buildings & Prosperity",
  skills: [
  {
      id: "township.buildings.1",
      prof: "township",
      branch: "buildings",
      rank: 1,
      name: "Frugal Builder",
      desc: "-10% building cost.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/smarts/11.png",
      signature: "Mason's Trowel",
      recipes: ["build_floor_modular", "build_wall_modular", "build_door_round"],
      passive: { "buildCostReduction": 0.1 },
      extras: {},
    },
  {
      id: "township.buildings.2",
      prof: "township",
      branch: "buildings",
      rank: 2,
      name: "Salvage Yard",
      desc: "+10% morale per building; unlocks Logging Camp (employs Woodcutter NPC, +5 wood/day passive).",
      cost: 2,
      prereq: ["township.buildings.1"],
      icon: "/icons/perks/smarts/12.png",
      signature: "Mason's Trowel",
      recipes: ["build_floor_brick", "build_floor_wood_dark", "build_window", "build_window_shutters", "build_doorframe_round", "build_logging_camp", "hire_woodcutter"],
      passive: { "campMoraleBonus": 0.1 },
      extras: { "harvesterUnlocked": "woodcutter" },
    },
  {
      id: "township.buildings.3",
      prof: "township",
      branch: "buildings",
      rank: 3,
      name: "Master Mason",
      desc: "-20% building cost (stacks); unlocks Mining Outpost (employs Miner NPC, +5 ore/day).",
      cost: 4,
      prereq: ["township.buildings.2"],
      icon: "/icons/perks/smarts/13.png",
      signature: "Mason's Trowel",
      recipes: ["build_roof_tile", "build_overhang_plaster", "build_balcony_simple", "build_stairs_modular", "build_mining_outpost", "hire_miner"],
      passive: { "buildCostReduction": 0.2 },
      extras: { "harvesterUnlocked": "miner" },
    },
  {
      id: "township.buildings.4",
      prof: "township",
      branch: "buildings",
      rank: 4,
      name: "Boomtown",
      desc: "-15% craft cost, +30% morale (stacks); unlocks Field (employs Farmer NPC, +5 herb/day).",
      cost: 8,
      prereq: ["township.buildings.3"],
      icon: "/icons/perks/smarts/14.png",
      signature: "Mason's Trowel",
      recipes: ["build_workbench_drawers", "build_armory_chest", "build_metal_fence", "build_overhang_uneven_brick", "build_balcony_cross", "build_keep_chimney", "build_field", "hire_farmer"],
      passive: { "craftCostReduction": 0.15, "campMoraleBonus": 0.3 },
      extras: { "harvesterUnlocked": "farmer" },
    },
  ],
};

const BR_TOWNSHIP_TRADE: ProfessionBranch = {
  id: "trade",
  prof: "township",
  label: "Trade",
  skills: [
  {
      id: "township.trade.1",
      prof: "township",
      branch: "trade",
      rank: 1,
      name: "Haggler",
      desc: "+10% gold from sales to NPCs; unlocks Stall Vendor hire (mans market stalls, auto-sells loot).",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/smarts/15.png",
      signature: "Merchant's Coinpurse",
      recipes: ["build_market_stall", "hire_stall_vendor"],
      passive: { "sellGoldBonus": 0.1 },
      extras: { "vendorUnlocked": "stall" },
    },
  {
      id: "township.trade.2",
      prof: "township",
      branch: "trade",
      rank: 2,
      name: "Caravan",
      desc: "Unlocks build_trade_post (passive 5 gold/day per post when staffed by Caravan Master).",
      cost: 2,
      prereq: ["township.trade.1"],
      icon: "/icons/perks/smarts/16.png",
      signature: "Merchant's Coinpurse",
      recipes: ["build_trade_post", "build_caravan_cart", "hire_caravan_master"],
      passive: { "passiveGoldRate": 5 },
      extras: { "vendorUnlocked": "caravan_master" },
    },
  {
      id: "township.trade.3",
      prof: "township",
      branch: "trade",
      rank: 3,
      name: "Black Market",
      desc: "Unlocks rare/contraband goods at township market stalls; unlocks Fence hire (buys stolen goods +50%).",
      cost: 4,
      prereq: ["township.trade.2"],
      icon: "/icons/perks/smarts/17.png",
      signature: "Merchant's Coinpurse",
      recipes: ["build_market_complex", "craft_smuggler_crate", "hire_fence"],
      passive: {},
      extras: { "blackMarketUnlocked": true, "vendorUnlocked": "fence" },
    },
  {
      id: "township.trade.4",
      prof: "township",
      branch: "trade",
      rank: 4,
      name: "Tycoon",
      desc: "+50% gold from all sources, passive +10 gold/day per trade post; Bazaar slots gain 3 Vendor hire slots.",
      cost: 8,
      prereq: ["township.trade.3"],
      icon: "/icons/perks/smarts/18.png",
      signature: "Merchant's Coinpurse / Gilded Ledger",
      recipes: ["build_grand_bazaar", "hire_bazaar_merchant"],
      passive: { "sellGoldBonus": 0.5, "passiveGoldRate": 10 },
      extras: { "vendorUnlocked": "bazaar_merchant" },
    },
  ],
};

const BR_TOWNSHIP_DIPLOMACY: ProfessionBranch = {
  id: "diplomacy",
  prof: "township",
  label: "Diplomacy",
  skills: [
  {
      id: "township.diplomacy.1",
      prof: "township",
      branch: "diplomacy",
      rank: 1,
      name: "Smooth Talker",
      desc: "Friendly NPCs heal you 1 hp/sec while in camp.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/hero/30.png",
      signature: "Diplomatic Scroll",
      recipes: [],
      passive: { "allyAuraHealRate": 1 },
      extras: {},
    },
  {
      id: "township.diplomacy.2",
      prof: "township",
      branch: "diplomacy",
      rank: 2,
      name: "Faction Standing",
      desc: "+10% reputation gain with all factions.",
      cost: 2,
      prereq: ["township.diplomacy.1"],
      icon: "/icons/perks/hero/31.png",
      signature: "Diplomatic Scroll",
      recipes: ["build_meeting_hall"],
      passive: { "reputationGainBonus": 0.1 },
      extras: {},
    },
  {
      id: "township.diplomacy.3",
      prof: "township",
      branch: "diplomacy",
      rank: 3,
      name: "Treaty Maker",
      desc: "Unlocks build_embassy (faction passive bonuses while built); unlocks Diplomat Envoy hire (mans embassy, +1 reputation/day).",
      cost: 4,
      prereq: ["township.diplomacy.2"],
      icon: "/icons/perks/hero/32.png",
      signature: "Diplomatic Scroll / Embassy Banner",
      recipes: ["build_embassy", "craft_treaty_seal", "hire_diplomat"],
      passive: {},
      extras: { "embassyUnlocked": true, "allyUnlocked": "diplomat" },
    },
  {
      id: "township.diplomacy.4",
      prof: "township",
      branch: "diplomacy",
      rank: 4,
      name: "Crown Bearer",
      desc: "Friendly factions send a gift caravan weekly.",
      cost: 8,
      prereq: ["township.diplomacy.3"],
      icon: "/icons/perks/hero/33.png",
      signature: "Diplomatic Scroll / Crown",
      recipes: ["build_throne", "build_diplomat_quarters"],
      passive: {},
      extras: { "factionGiftWeekly": true },
    },
  ],
};

const BR_TOWNSHIP_DEFENSES: ProfessionBranch = {
  id: "defenses",
  prof: "township",
  label: "Defenses",
  skills: [
  {
      id: "township.defenses.1",
      prof: "township",
      branch: "defenses",
      rank: 1,
      name: "Watchful",
      desc: "Unlocks build_watchtower; +25% camp NPC alert range; unlocks Sentry hire (mans watchtower, ranged alert).",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/warrior/31.png",
      signature: "Turret Schematic",
      recipes: ["build_watchtower", "hire_sentry"],
      passive: { "npcAlertRange": 0.25 },
      extras: { "watchtowerUnlocked": true, "allyUnlocked": "sentry" },
    },
  {
      id: "township.defenses.2",
      prof: "township",
      branch: "defenses",
      rank: 2,
      name: "Sturdy Walls",
      desc: "Placed walls have +50% HP; unlocks Gate Guard hire pair (patrols gates/palisade).",
      cost: 2,
      prereq: ["township.defenses.1"],
      icon: "/icons/perks/warrior/32.png",
      signature: "Turret Schematic",
      recipes: ["build_palisade", "build_gate_iron", "hire_gate_guard"],
      passive: { "wallHpBonus": 0.5 },
      extras: { "allyUnlocked": "gate_guard" },
    },
  {
      id: "township.defenses.3",
      prof: "township",
      branch: "defenses",
      rank: 3,
      name: "Auto-Turret",
      desc: "Unlocks build_turret_basic (auto-fires at hostiles in range); unlocks Turret Gunner hire (+30% accuracy / +20% rate while assigned).",
      cost: 4,
      prereq: ["township.defenses.2"],
      icon: "/icons/perks/warrior/33.png",
      signature: "Turret Schematic / Turret Toolkit",
      recipes: ["build_turret_basic", "craft_turret_ammo", "hire_gunner"],
      passive: {},
      extras: { "turretBasicUnlocked": true, "allyUnlocked": "gunner" },
    },
  {
      id: "township.defenses.4",
      prof: "township",
      branch: "defenses",
      rank: 4,
      name: "Fortress",
      desc: "+25% all camp building HP, turrets +50% damage; unlocks Captain hire (elite party companion + 3-NPC squad).",
      cost: 8,
      prereq: ["township.defenses.3"],
      icon: "/icons/perks/warrior/34.png",
      signature: "Turret Schematic / Fortress Keystone",
      recipes: ["build_turret_heavy", "build_keep_gate", "hire_captain"],
      passive: { "buildingHpBonus": 0.25, "turretDamageBonus": 0.5 },
      extras: { "allyUnlocked": "captain" },
    },
  ],
};

const MASTER_TOWNSHIP: ProfessionMaster = {
      id: "township.master",
      prof: "township",
      branch: "master",
      rank: "M",
      name: "Lord of the Township",
      desc: "PROFESSION MASTER — +3 recruits, +25% morale, -25% build cost, all unlocks active. Requires Leadership 4 + Buildings 4 + Trade 4 + Diplomacy 4 + Defenses 4.",
      cost: 20,
      prereq: ["township.leadership.4", "township.buildings.4", "township.trade.4", "township.diplomacy.4", "township.defenses.4"],
      icon: "/icons/perks/hero/9.png",
      signature: "Lord's Banner",
      recipes: ["build_command_tent", "build_lords_hall"],
      passive: { "recruitCapBonus": 3, "campMoraleBonus": 0.25, "buildCostReduction": 0.25, "sellGoldBonus": 0.25 },
      extras: {},
    };

const BR_SURVIVAL_TRAINING: ProfessionBranch = {
  id: "training",
  prof: "survival",
  label: "Combat Training",
  skills: [
  {
      id: "survival.training.1",
      prof: "survival",
      branch: "training",
      rank: 1,
      name: "Conditioning",
      desc: "+10 max HP.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/smarts/21.png",
      signature: "Training Sword",
      recipes: [],
      passive: { "maxHpBonus": 10 },
      extras: {},
    },
  {
      id: "survival.training.2",
      prof: "survival",
      branch: "training",
      rank: 2,
      name: "Wind Sprints",
      desc: "+15% stamina regen.",
      cost: 2,
      prereq: ["survival.training.1"],
      icon: "/icons/perks/smarts/22.png",
      signature: "Training Sword",
      recipes: [],
      passive: { "staminaRegenBonus": 0.15 },
      extras: {},
    },
  {
      id: "survival.training.3",
      prof: "survival",
      branch: "training",
      rank: 3,
      name: "Iron Skin",
      desc: "+5% damage reduction.",
      cost: 4,
      prereq: ["survival.training.2"],
      icon: "/icons/perks/smarts/23.png",
      signature: "Training Sword",
      recipes: [],
      passive: { "damageReductionBonus": 0.05 },
      extras: {},
    },
  {
      id: "survival.training.4",
      prof: "survival",
      branch: "training",
      rank: 4,
      name: "Battle-Scarred",
      desc: "+25 max HP, +15% damage reduction (stacks).",
      cost: 8,
      prereq: ["survival.training.3"],
      icon: "/icons/perks/smarts/24.png",
      signature: "Training Sword",
      recipes: [],
      passive: { "maxHpBonus": 25, "damageReductionBonus": 0.15 },
      extras: {},
    },
  ],
};

const BR_SURVIVAL_RESOLVE: ProfessionBranch = {
  id: "resolve",
  prof: "survival",
  label: "Resolve",
  skills: [
  {
      id: "survival.resolve.1",
      prof: "survival",
      branch: "resolve",
      rank: 1,
      name: "Second Wind",
      desc: "+15% stamina regen.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/hero/34.png",
      signature: "Heavy Pack",
      recipes: [],
      passive: { "staminaRegenBonus": 0.15 },
      extras: {},
    },
  {
      id: "survival.resolve.2",
      prof: "survival",
      branch: "resolve",
      rank: 2,
      name: "Set Jaw",
      desc: "+15 max HP.",
      cost: 2,
      prereq: ["survival.resolve.1"],
      icon: "/icons/perks/hero/35.png",
      signature: "Heavy Pack",
      recipes: [],
      passive: { "maxHpBonus": 15 },
      extras: {},
    },
  {
      id: "survival.resolve.3",
      prof: "survival",
      branch: "resolve",
      rank: 3,
      name: "Unyielding",
      desc: "+10% damage reduction.",
      cost: 4,
      prereq: ["survival.resolve.2"],
      icon: "/icons/perks/hero/36.png",
      signature: "Heavy Pack",
      recipes: [],
      passive: { "damageReductionBonus": 0.1 },
      extras: {},
    },
  {
      id: "survival.resolve.4",
      prof: "survival",
      branch: "resolve",
      rank: 4,
      name: "Indomitable",
      desc: "+30 max HP, +20% damage reduction (stacks).",
      cost: 8,
      prereq: ["survival.resolve.3"],
      icon: "/icons/perks/hero/37.png",
      signature: "Heavy Pack",
      recipes: [],
      passive: { "maxHpBonus": 30, "damageReductionBonus": 0.2 },
      extras: {},
    },
  ],
};

const BR_SURVIVAL_ENDURANCE: ProfessionBranch = {
  id: "endurance",
  prof: "survival",
  label: "Endurance",
  skills: [
  {
      id: "survival.endurance.1",
      prof: "survival",
      branch: "endurance",
      rank: 1,
      name: "Camel",
      desc: "+25% food and water buff duration.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/smarts/25.png",
      signature: "Waterskin",
      recipes: ["craft_waterskin"],
      passive: { "foodBuffDurationBonus": 0.25 },
      extras: {},
    },
  {
      id: "survival.endurance.2",
      prof: "survival",
      branch: "endurance",
      rank: 2,
      name: "Marathoner",
      desc: "Sprint costs -20% stamina.",
      cost: 2,
      prereq: ["survival.endurance.1"],
      icon: "/icons/perks/smarts/26.png",
      signature: "Waterskin",
      recipes: [],
      passive: { "sprintCostReduction": 0.2 },
      extras: {},
    },
  {
      id: "survival.endurance.3",
      prof: "survival",
      branch: "endurance",
      rank: 3,
      name: "Iron Stomach",
      desc: "Eat raw food without penalty; +10% all food yield consumed.",
      cost: 4,
      prereq: ["survival.endurance.2"],
      icon: "/icons/perks/smarts/27.png",
      signature: "Waterskin",
      recipes: [],
      passive: { "foodEffectBonus": 0.1 },
      extras: { "rawFoodPenaltyImmunity": true },
    },
  {
      id: "survival.endurance.4",
      prof: "survival",
      branch: "endurance",
      rank: 4,
      name: "Eternal Wanderer",
      desc: "Passive +1 hp/sec out of combat, +25% food duration (stacks).",
      cost: 8,
      prereq: ["survival.endurance.3"],
      icon: "/icons/perks/smarts/28.png",
      signature: "Waterskin / Camp Kettle",
      recipes: ["craft_camp_kettle"],
      passive: { "oocHealRate": 1, "foodBuffDurationBonus": 0.25 },
      extras: {},
    },
  ],
};

const BR_SURVIVAL_WILDERNESS: ProfessionBranch = {
  id: "wilderness",
  prof: "survival",
  label: "Wilderness",
  skills: [
  {
      id: "survival.wilderness.1",
      prof: "survival",
      branch: "wilderness",
      rank: 1,
      name: "Layered Furs",
      desc: "-50% cold damage in tundra.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/smarts/29.png",
      signature: "Survivor's Cloak",
      recipes: [],
      passive: { "coldResistBonus": 0.5 },
      extras: {},
    },
  {
      id: "survival.wilderness.2",
      prof: "survival",
      branch: "wilderness",
      rank: 2,
      name: "Sunbleached",
      desc: "-50% heat damage in desert.",
      cost: 2,
      prereq: ["survival.wilderness.1"],
      icon: "/icons/perks/smarts/30.png",
      signature: "Survivor's Cloak",
      recipes: [],
      passive: { "heatResistBonus": 0.5 },
      extras: {},
    },
  {
      id: "survival.wilderness.3",
      prof: "survival",
      branch: "wilderness",
      rank: 3,
      name: "Rad Suit",
      desc: "-50% radiation damage in rift zones.",
      cost: 4,
      prereq: ["survival.wilderness.2"],
      icon: "/icons/perks/smarts/31.png",
      signature: "Survivor's Cloak / Rad Suit",
      recipes: ["craft_rad_suit"],
      passive: { "radResistBonus": 0.5 },
      extras: {},
    },
  {
      id: "survival.wilderness.4",
      prof: "survival",
      branch: "wilderness",
      rank: 4,
      name: "Element-Forged",
      desc: "+25% damage in any biome you have full resist for, biome resists stack.",
      cost: 8,
      prereq: ["survival.wilderness.3"],
      icon: "/icons/perks/smarts/32.png",
      signature: "Survivor's Cloak / Elementforged Cloak",
      recipes: ["craft_elementforged_cloak"],
      passive: { "biomeDamageBonus": 0.25 },
      extras: { "allResistsStack": true },
    },
  ],
};

const BR_SURVIVAL_VETERANCY: ProfessionBranch = {
  id: "veterancy",
  prof: "survival",
  label: "Veterancy",
  skills: [
  {
      id: "survival.veterancy.1",
      prof: "survival",
      branch: "veterancy",
      rank: 1,
      name: "Bronze Mark",
      desc: "+5% XP from all sources.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/smarts/33.png",
      signature: "Veteran's Medal",
      recipes: [],
      passive: { "bountyXpBonus": 0.05 },
      extras: {},
    },
  {
      id: "survival.veterancy.2",
      prof: "survival",
      branch: "veterancy",
      rank: 2,
      name: "Silver Mark",
      desc: "+10% XP (stacks).",
      cost: 2,
      prereq: ["survival.veterancy.1"],
      icon: "/icons/perks/smarts/34.png",
      signature: "Veteran's Medal",
      recipes: [],
      passive: { "bountyXpBonus": 0.1 },
      extras: {},
    },
  {
      id: "survival.veterancy.3",
      prof: "survival",
      branch: "veterancy",
      rank: 3,
      name: "Gold Mark",
      desc: "+20% XP (stacks).",
      cost: 4,
      prereq: ["survival.veterancy.2"],
      icon: "/icons/perks/smarts/35.png",
      signature: "Veteran's Medal",
      recipes: [],
      passive: { "bountyXpBonus": 0.2 },
      extras: {},
    },
  {
      id: "survival.veterancy.4",
      prof: "survival",
      branch: "veterancy",
      rank: 4,
      name: "Platinum Mark",
      desc: "+15% damage reduction, +50 max HP (stacks).",
      cost: 8,
      prereq: ["survival.veterancy.3"],
      icon: "/icons/perks/smarts/36.png",
      signature: "Veteran's Medal",
      recipes: [],
      passive: { "damageReductionBonus": 0.15, "maxHpBonus": 50 },
      extras: {},
    },
  ],
};

const MASTER_SURVIVAL: ProfessionMaster = {
      id: "survival.master",
      prof: "survival",
      branch: "master",
      rank: "M",
      name: "Rift-Mark",
      desc: "PROFESSION MASTER — +75 max HP, +25% DR, +25% stamina regen, +25% XP, all biome resists max, all unlocks active. Requires Training 4 + Resolve 4 + Endurance 4 + Wilderness 4 + Veterancy 4.",
      cost: 20,
      prereq: ["survival.training.4", "survival.resolve.4", "survival.endurance.4", "survival.wilderness.4", "survival.veterancy.4"],
      icon: "/icons/perks/smarts/37.png",
      signature: "Veteran's Crest",
      recipes: ["craft_riftmark_amulet"],
      passive: { "maxHpBonus": 75, "damageReductionBonus": 0.25, "staminaRegenBonus": 0.25, "bountyXpBonus": 0.25 },
      extras: { "allResistsStack": true },
    };

const BR_CHEMISTRY_GROWTH: ProfessionBranch = {
  id: "growth",
  prof: "chemistry",
  label: "Cooking",
  skills: [
  {
      id: "chemistry.growth.1",
      prof: "chemistry",
      branch: "growth",
      rank: 1,
      name: "Hot Plate",
      desc: "+10% cooked food yield.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/maker/41.png",
      signature: "Cooking Pan",
      recipes: ["cook_meat", "cook_fish", "cook_berry_jam"],
      passive: { "cookingYieldBonus": 0.1 },
      extras: {},
    },
  {
      id: "chemistry.growth.2",
      prof: "chemistry",
      branch: "growth",
      rank: 2,
      name: "Hearty Stew",
      desc: "+25% food buff duration.",
      cost: 2,
      prereq: ["chemistry.growth.1"],
      icon: "/icons/perks/maker/42.png",
      signature: "Cooking Pan",
      recipes: ["cook_stew", "cook_grain_porridge", "cook_roast_corn"],
      passive: { "foodBuffDurationBonus": 0.25 },
      extras: {},
    },
  {
      id: "chemistry.growth.3",
      prof: "chemistry",
      branch: "growth",
      rank: 3,
      name: "Camp Chef",
      desc: "+20% food yield (stacks).",
      cost: 4,
      prereq: ["chemistry.growth.2"],
      icon: "/icons/perks/maker/43.png",
      signature: "Cooking Pan",
      recipes: ["cook_roast_meat", "cook_fish_filet_grilled", "cook_mushroom_skewer"],
      passive: { "cookingYieldBonus": 0.2 },
      extras: {},
    },
  {
      id: "chemistry.growth.4",
      prof: "chemistry",
      branch: "growth",
      rank: 4,
      name: "Master of the Pot",
      desc: "+50% food duration, +30% yield (stacks).",
      cost: 8,
      prereq: ["chemistry.growth.3"],
      icon: "/icons/perks/maker/44.png",
      signature: "Cooking Pan",
      recipes: ["cook_hunters_pie", "cook_camp_feast", "cook_stratocolony_ration"],
      passive: { "foodBuffDurationBonus": 0.5, "cookingYieldBonus": 0.3 },
      extras: {},
    },
  ],
};

const BR_CHEMISTRY_GOOS: ProfessionBranch = {
  id: "goos",
  prof: "chemistry",
  label: "Goos (Potions)",
  skills: [
  {
      id: "chemistry.goos.1",
      prof: "chemistry",
      branch: "goos",
      rank: 1,
      name: "Quick Brew",
      desc: "+10% potion potency.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/maker/45.png",
      signature: "Mortar & Pestle",
      recipes: ["brew_minor_health", "brew_water_purified"],
      passive: { "potionPotencyBonus": 0.1 },
      extras: {},
    },
  {
      id: "chemistry.goos.2",
      prof: "chemistry",
      branch: "goos",
      rank: 2,
      name: "Pure Reagents",
      desc: "+15% potion potency (stacks).",
      cost: 2,
      prereq: ["chemistry.goos.1"],
      icon: "/icons/perks/maker/46.png",
      signature: "Mortar & Pestle",
      recipes: ["brew_stamina_potion", "brew_minor_antidote"],
      passive: { "potionPotencyBonus": 0.15 },
      extras: {},
    },
  {
      id: "chemistry.goos.3",
      prof: "chemistry",
      branch: "goos",
      rank: 3,
      name: "Stabilizer",
      desc: "+25% potion duration.",
      cost: 4,
      prereq: ["chemistry.goos.2"],
      icon: "/icons/perks/maker/47.png",
      signature: "Mortar & Pestle",
      recipes: ["brew_health_potion", "brew_speed_tonic"],
      passive: { "foodBuffDurationBonus": 0.25 },
      extras: {},
    },
  {
      id: "chemistry.goos.4",
      prof: "chemistry",
      branch: "goos",
      rank: 4,
      name: "Master Alchemist",
      desc: "+25% potion potency, +50% potency stack.",
      cost: 8,
      prereq: ["chemistry.goos.3"],
      icon: "/icons/perks/maker/48.png",
      signature: "Mortar & Pestle",
      recipes: ["brew_greater_health", "brew_radiation_resist", "brew_invisibility_draught", "brew_crystal_x_essence"],
      passive: { "potionPotencyBonus": 0.5 },
      extras: {},
    },
  ],
};

const BR_CHEMISTRY_DEMO: ProfessionBranch = {
  id: "demo",
  prof: "chemistry",
  label: "Demolitions",
  skills: [
  {
      id: "chemistry.demo.1",
      prof: "chemistry",
      branch: "demo",
      rank: 1,
      name: "Sapper",
      desc: "+20% explosion damage from grenades and charges.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/warrior/41.png",
      signature: "Detonator",
      recipes: ["craft_grenade_frag"],
      passive: { "explosionDamageBonus": 0.2 },
      extras: {},
    },
  {
      id: "chemistry.demo.2",
      prof: "chemistry",
      branch: "demo",
      rank: 2,
      name: "Flashfire",
      desc: "Explosions ignite enemies for 5s (5 dmg/s).",
      cost: 2,
      prereq: ["chemistry.demo.1"],
      icon: "/icons/perks/warrior/42.png",
      signature: "Detonator",
      recipes: ["craft_grenade_incendiary", "craft_grenade_smoke"],
      passive: {},
      extras: { "igniteOnExplosion": true },
    },
  {
      id: "chemistry.demo.3",
      prof: "chemistry",
      branch: "demo",
      rank: 3,
      name: "Sticky Bomb",
      desc: "Unlock craft_satchel_charge; charges adhere to surfaces.",
      cost: 4,
      prereq: ["chemistry.demo.2"],
      icon: "/icons/perks/warrior/43.png",
      signature: "Detonator / Sapper's Spade",
      recipes: ["craft_satchel_charge", "craft_landmine"],
      passive: {},
      extras: { "satchelChargeUnlocked": true },
    },
  {
      id: "chemistry.demo.4",
      prof: "chemistry",
      branch: "demo",
      rank: 4,
      name: "Annihilator",
      desc: "+50% blast radius, +25% damage (stacks).",
      cost: 8,
      prereq: ["chemistry.demo.3"],
      icon: "/icons/perks/warrior/44.png",
      signature: "Detonator / Rift Charge",
      recipes: ["craft_grenade_rift", "craft_breaching_charge"],
      passive: { "explosionRadiusBonus": 0.5, "explosionDamageBonus": 0.25 },
      extras: {},
    },
  ],
};

const BR_CHEMISTRY_TOX: ProfessionBranch = {
  id: "tox",
  prof: "chemistry",
  label: "Toxicology",
  skills: [
  {
      id: "chemistry.tox.1",
      prof: "chemistry",
      branch: "tox",
      rank: 1,
      name: "Poisoner",
      desc: "Coated weapons deal +5 poison/sec for 10s.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/warrior/45.png",
      signature: "Venom Vial",
      recipes: ["brew_poison_vial"],
      passive: { "weaponPoisonOnHit": 5 },
      extras: {},
    },
  {
      id: "chemistry.tox.2",
      prof: "chemistry",
      branch: "tox",
      rank: 2,
      name: "Gas Cloud",
      desc: "Unlock craft_gas_grenade (10m AoE 8 dmg/s).",
      cost: 2,
      prereq: ["chemistry.tox.1"],
      icon: "/icons/perks/warrior/46.png",
      signature: "Venom Vial",
      recipes: ["craft_gas_grenade", "brew_corrosive_oil"],
      passive: {},
      extras: { "gasGrenadeUnlocked": true },
    },
  {
      id: "chemistry.tox.3",
      prof: "chemistry",
      branch: "tox",
      rank: 3,
      name: "Acid Bath",
      desc: "Poisons reduce enemy DR by 25%.",
      cost: 4,
      prereq: ["chemistry.tox.2"],
      icon: "/icons/perks/warrior/47.png",
      signature: "Venom Vial",
      recipes: ["brew_acid_flask", "craft_poison_dart_pack"],
      passive: { "poisonArmourPenetration": 0.25 },
      extras: {},
    },
  {
      id: "chemistry.tox.4",
      prof: "chemistry",
      branch: "tox",
      rank: 4,
      name: "Plague Bearer",
      desc: "Unlock craft_plague_vial (AoE DoT lasting 30s).",
      cost: 8,
      prereq: ["chemistry.tox.3"],
      icon: "/icons/perks/warrior/48.png",
      signature: "Venom Vial / Plague Censer",
      recipes: ["craft_plague_vial", "brew_venom_concentrate"],
      passive: {},
      extras: { "plagueVialUnlocked": true },
    },
  ],
};

const BR_CHEMISTRY_REFINING: ProfessionBranch = {
  id: "refining",
  prof: "chemistry",
  label: "Refining",
  skills: [
  {
      id: "chemistry.refining.1",
      prof: "chemistry",
      branch: "refining",
      rank: 1,
      name: "Smelter",
      desc: "+20% iron→ingot yield at smelter.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/maker/49.png",
      signature: "Crucible Tongs",
      recipes: ["build_smelter"],
      passive: { "smeltYieldBonus": 0.2 },
      extras: {},
    },
  {
      id: "chemistry.refining.2",
      prof: "chemistry",
      branch: "refining",
      rank: 2,
      name: "Distiller",
      desc: "+20% herb→reagent yield at workbench.",
      cost: 2,
      prereq: ["chemistry.refining.1"],
      icon: "/icons/perks/maker/50.png",
      signature: "Crucible Tongs",
      recipes: ["craft_distiller"],
      passive: { "distillYieldBonus": 0.2 },
      extras: {},
    },
  {
      id: "chemistry.refining.3",
      prof: "chemistry",
      branch: "refining",
      rank: 3,
      name: "Crucible",
      desc: "Refining at workbench gives 2× output.",
      cost: 4,
      prereq: ["chemistry.refining.2"],
      icon: "/icons/perks/maker/51.png",
      signature: "Crucible Tongs / Furnace Bellows",
      recipes: ["build_crucible", "craft_purified_ore"],
      passive: {},
      extras: { "refineDoubleOutput": true },
    },
  {
      id: "chemistry.refining.4",
      prof: "chemistry",
      branch: "refining",
      rank: 4,
      name: "Transmuter",
      desc: "Unlock iron→steel and copper→bronze transmutation recipes.",
      cost: 8,
      prereq: ["chemistry.refining.3"],
      icon: "/icons/perks/maker/52.png",
      signature: "Crucible Tongs / Transmuter's Wand",
      recipes: ["craft_iron_to_steel", "craft_copper_to_bronze", "craft_crystal_to_attuned"],
      passive: {},
      extras: { "transmutationUnlocked": true },
    },
  ],
};

const MASTER_CHEMISTRY: ProfessionMaster = {
      id: "chemistry.master",
      prof: "chemistry",
      branch: "master",
      rank: "M",
      name: "Pact of the Goos",
      desc: "PROFESSION MASTER — +50% potion potency, +50% food duration, +25% cooking yield, +50% explosion radius, all unlocks active. Requires Cooking 4 + Goos 4 + Demolitions 4 + Toxicology 4 + Refining 4.",
      cost: 20,
      prereq: ["chemistry.growth.4", "chemistry.goos.4", "chemistry.demo.4", "chemistry.tox.4", "chemistry.refining.4"],
      icon: "/icons/perks/maker/53.png",
      signature: "Master's Cauldron",
      recipes: ["brew_elixir_eternity", "cook_kings_table", "craft_pact_charm"],
      passive: { "potionPotencyBonus": 0.5, "foodBuffDurationBonus": 0.5, "cookingYieldBonus": 0.25, "explosionRadiusBonus": 0.5 },
      extras: {},
    };

const BR_COMBAT_PISTOL: ProfessionBranch = {
  id: "pistol",
  prof: "combat",
  label: "Pistol",
  skills: [
  {
      id: "combat.pistol.1",
      prof: "combat",
      branch: "pistol",
      rank: 1,
      name: "Steady Aim",
      desc: "+5% pistol damage.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/warrior/51.png",
      signature: "Any Pistol (Pistol_1–3 / Revolver)",
      recipes: [],
      passive: { "pistolDamageBonus": 0.05 },
      extras: {},
    },
  {
      id: "combat.pistol.2",
      prof: "combat",
      branch: "pistol",
      rank: 2,
      name: "Quick Reload",
      desc: "+20% pistol reload speed.",
      cost: 2,
      prereq: ["combat.pistol.1"],
      icon: "/icons/perks/warrior/52.png",
      signature: "Any Pistol",
      recipes: [],
      passive: { "pistolReloadSpeedBonus": 0.2 },
      extras: {},
    },
  {
      id: "combat.pistol.3",
      prof: "combat",
      branch: "pistol",
      rank: 3,
      name: "Twin Shot",
      desc: "+15% pistol damage (stacks).",
      cost: 4,
      prereq: ["combat.pistol.2"],
      icon: "/icons/perks/warrior/53.png",
      signature: "Any Pistol",
      recipes: [],
      passive: { "pistolDamageBonus": 0.15 },
      extras: {},
    },
  {
      id: "combat.pistol.4",
      prof: "combat",
      branch: "pistol",
      rank: 4,
      name: "Gunslinger",
      desc: "+25% pistol damage, +25% crit chance (stacks).",
      cost: 8,
      prereq: ["combat.pistol.3"],
      icon: "/icons/perks/warrior/54.png",
      signature: "Any Pistol / Revolver",
      recipes: [],
      passive: { "pistolDamageBonus": 0.25, "pistolCritBonus": 0.25 },
      extras: {},
    },
  ],
};

const BR_COMBAT_RIFLE: ProfessionBranch = {
  id: "rifle",
  prof: "combat",
  label: "Rifle",
  skills: [
  {
      id: "combat.rifle.1",
      prof: "combat",
      branch: "rifle",
      rank: 1,
      name: "True Shot",
      desc: "+5% rifle damage.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/warrior/55.png",
      signature: "Any Rifle (AssaultRifle / SniperRifle / Bullpup)",
      recipes: [],
      passive: { "rifleDamageBonus": 0.05 },
      extras: {},
    },
  {
      id: "combat.rifle.2",
      prof: "combat",
      branch: "rifle",
      rank: 2,
      name: "Scope Discipline",
      desc: "+25% rifle accuracy at range.",
      cost: 2,
      prereq: ["combat.rifle.1"],
      icon: "/icons/perks/warrior/56.png",
      signature: "Any Rifle",
      recipes: [],
      passive: { "rifleAccuracyBonus": 0.25 },
      extras: {},
    },
  {
      id: "combat.rifle.3",
      prof: "combat",
      branch: "rifle",
      rank: 3,
      name: "Heavy Slug",
      desc: "+15% rifle damage (stacks).",
      cost: 4,
      prereq: ["combat.rifle.2"],
      icon: "/icons/perks/warrior/57.png",
      signature: "Any Rifle",
      recipes: [],
      passive: { "rifleDamageBonus": 0.15 },
      extras: {},
    },
  {
      id: "combat.rifle.4",
      prof: "combat",
      branch: "rifle",
      rank: 4,
      name: "Rifleman",
      desc: "+25% rifle damage, +50% headshot damage (stacks).",
      cost: 8,
      prereq: ["combat.rifle.3"],
      icon: "/icons/perks/warrior/58.png",
      signature: "Any Rifle / Sniper",
      recipes: [],
      passive: { "rifleDamageBonus": 0.25, "rifleHeadshotBonus": 0.5 },
      extras: {},
    },
  ],
};

const BR_COMBAT_BLADES: ProfessionBranch = {
  id: "blades",
  prof: "combat",
  label: "Blades",
  skills: [
  {
      id: "combat.blades.1",
      prof: "combat",
      branch: "blades",
      rank: 1,
      name: "First Cut",
      desc: "+5% blade damage in hand.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/warrior/61.png",
      signature: "Any Sword / Dagger / Scythe",
      recipes: [],
      passive: { "bladeUseDamageBonus": 0.05 },
      extras: {},
    },
  {
      id: "combat.blades.2",
      prof: "combat",
      branch: "blades",
      rank: 2,
      name: "Footwork",
      desc: "+15% blade attack speed.",
      cost: 2,
      prereq: ["combat.blades.1"],
      icon: "/icons/perks/warrior/62.png",
      signature: "Any Sword / Dagger",
      recipes: [],
      passive: { "bladeAttackSpeedBonus": 0.15 },
      extras: {},
    },
  {
      id: "combat.blades.3",
      prof: "combat",
      branch: "blades",
      rank: 3,
      name: "Riposte",
      desc: "+15% blade damage (stacks), parry restores stamina.",
      cost: 4,
      prereq: ["combat.blades.2"],
      icon: "/icons/perks/warrior/63.png",
      signature: "Any Sword / Dagger",
      recipes: [],
      passive: { "bladeUseDamageBonus": 0.15, "parryStaminaBonus": 0.1 },
      extras: {},
    },
  {
      id: "combat.blades.4",
      prof: "combat",
      branch: "blades",
      rank: 4,
      name: "Swordmaster",
      desc: "+25% blade damage, +20% blade crit damage (stacks).",
      cost: 8,
      prereq: ["combat.blades.3"],
      icon: "/icons/perks/warrior/64.png",
      signature: "Claymore / Sword_Big / Sword_Golden",
      recipes: [],
      passive: { "bladeUseDamageBonus": 0.25, "bladeCritDamageBonus": 0.2 },
      extras: {},
    },
  ],
};

const BR_COMBAT_HAMMERS: ProfessionBranch = {
  id: "hammers",
  prof: "combat",
  label: "Hammers",
  skills: [
  {
      id: "combat.hammers.1",
      prof: "combat",
      branch: "hammers",
      rank: 1,
      name: "Solid Strike",
      desc: "+5% hammer/axe damage.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/warrior/65.png",
      signature: "Any Hammer / Axe",
      recipes: [],
      passive: { "hammerUseDamageBonus": 0.05 },
      extras: {},
    },
  {
      id: "combat.hammers.2",
      prof: "combat",
      branch: "hammers",
      rank: 2,
      name: "Concussive",
      desc: "+20% chance to stagger on hit.",
      cost: 2,
      prereq: ["combat.hammers.1"],
      icon: "/icons/perks/warrior/66.png",
      signature: "Any Hammer / Axe",
      recipes: [],
      passive: { "staggerChanceBonus": 0.2 },
      extras: {},
    },
  {
      id: "combat.hammers.3",
      prof: "combat",
      branch: "hammers",
      rank: 3,
      name: "Crushing Blow",
      desc: "+15% hammer/axe damage (stacks).",
      cost: 4,
      prereq: ["combat.hammers.2"],
      icon: "/icons/perks/warrior/67.png",
      signature: "Any Hammer / Axe",
      recipes: [],
      passive: { "hammerUseDamageBonus": 0.15 },
      extras: {},
    },
  {
      id: "combat.hammers.4",
      prof: "combat",
      branch: "hammers",
      rank: 4,
      name: "Skull-Splitter",
      desc: "+25% damage, +50% damage to shielded enemies (stacks).",
      cost: 8,
      prereq: ["combat.hammers.3"],
      icon: "/icons/perks/warrior/68.png",
      signature: "Hammer_Double / Axe_Double / War Hammer",
      recipes: [],
      passive: { "hammerUseDamageBonus": 0.25, "shieldBreakBonus": 0.5 },
      extras: {},
    },
  ],
};

const BR_COMBAT_THEFT: ProfessionBranch = {
  id: "theft",
  prof: "combat",
  label: "Theft",
  skills: [
  {
      id: "combat.theft.1",
      prof: "combat",
      branch: "theft",
      rank: 1,
      name: "Light Fingers",
      desc: "Unlocks pickpocket; +25% pickpocket success.",
      cost: 1,
      prereq: [],
      icon: "/icons/perks/smarts/41.png",
      signature: "Dagger / Knife (concealed)",
      recipes: [],
      passive: { "pickpocketYieldBonus": 0.25 },
      extras: {},
    },
  {
      id: "combat.theft.2",
      prof: "combat",
      branch: "theft",
      rank: 2,
      name: "Lockbreaker",
      desc: "+30% lockpick speed.",
      cost: 2,
      prereq: ["combat.theft.1"],
      icon: "/icons/perks/smarts/42.png",
      signature: "Lockpick / Dagger",
      recipes: ["craft_lockpick_set"],
      passive: { "lockpickSpeedBonus": 0.3 },
      extras: {},
    },
  {
      id: "combat.theft.3",
      prof: "combat",
      branch: "theft",
      rank: 3,
      name: "Cutpurse",
      desc: "+50% gold from pickpocket, +25% stealth.",
      cost: 4,
      prereq: ["combat.theft.2"],
      icon: "/icons/perks/smarts/43.png",
      signature: "Dagger",
      recipes: [],
      passive: { "pickpocketYieldBonus": 0.5, "stealthBonus": 0.25 },
      extras: {},
    },
  {
      id: "combat.theft.4",
      prof: "combat",
      branch: "theft",
      rank: 4,
      name: "Phantom",
      desc: "-30% stealth detection radius, +50% backstab damage.",
      cost: 8,
      prereq: ["combat.theft.3"],
      icon: "/icons/perks/smarts/44.png",
      signature: "Dagger / Dagger_2",
      recipes: ["craft_smoke_cloak"],
      passive: { "stealthBonus": 0.3, "backstabDamageBonus": 0.5 },
      extras: {},
    },
  ],
};

const MASTER_COMBAT: ProfessionMaster = {
      id: "combat.master",
      prof: "combat",
      branch: "master",
      rank: "M",
      name: "Apex Combatant",
      desc: "PROFESSION MASTER — +15% all weapon damage, +15% crit, +15% reload, +15% stealth, +50 max HP. Requires Pistol 4 + Rifle 4 + Blades 4 + Hammers 4 + Theft 4.",
      cost: 20,
      prereq: ["combat.pistol.4", "combat.rifle.4", "combat.blades.4", "combat.hammers.4", "combat.theft.4"],
      icon: "/icons/perks/warrior/69.png",
      signature: "Master's Mantle (any signature)",
      recipes: [],
      passive: { "pistolDamageBonus": 0.15, "rifleDamageBonus": 0.15, "bladeUseDamageBonus": 0.15, "hammerUseDamageBonus": 0.15, "pistolCritBonus": 0.15, "pistolReloadSpeedBonus": 0.15, "stealthBonus": 0.15, "maxHpBonus": 50 },
      extras: {},
    };

export const PROFESSION_BRANCHES: Record<Profession, ProfessionBranch[]> = {
  gathering: [BR_GATHERING_FORESTRY, BR_GATHERING_MINING, BR_GATHERING_PERMAFROST, BR_GATHERING_CRYSTALS, BR_GATHERING_SALVAGE],
  hunting: [BR_HUNTING_FISHING, BR_HUNTING_ANIMALS, BR_HUNTING_BOUNTY, BR_HUNTING_TRACKING, BR_HUNTING_TRAPPING],
  crafting: [BR_CRAFTING_EQUIPMENT, BR_CRAFTING_BLADESMITH, BR_CRAFTING_GUNSMITH, BR_CRAFTING_ARMOUR, BR_CRAFTING_TINKERING],
  township: [BR_TOWNSHIP_LEADERSHIP, BR_TOWNSHIP_BUILDINGS, BR_TOWNSHIP_TRADE, BR_TOWNSHIP_DIPLOMACY, BR_TOWNSHIP_DEFENSES],
  survival: [BR_SURVIVAL_TRAINING, BR_SURVIVAL_RESOLVE, BR_SURVIVAL_ENDURANCE, BR_SURVIVAL_WILDERNESS, BR_SURVIVAL_VETERANCY],
  chemistry: [BR_CHEMISTRY_GROWTH, BR_CHEMISTRY_GOOS, BR_CHEMISTRY_DEMO, BR_CHEMISTRY_TOX, BR_CHEMISTRY_REFINING],
  combat: [BR_COMBAT_PISTOL, BR_COMBAT_RIFLE, BR_COMBAT_BLADES, BR_COMBAT_HAMMERS, BR_COMBAT_THEFT],
};

export const PROFESSION_MASTERS: Record<Profession, ProfessionMaster | null> = {
  gathering: MASTER_GATHERING,
  hunting: MASTER_HUNTING,
  crafting: MASTER_CRAFTING,
  township: MASTER_TOWNSHIP,
  survival: MASTER_SURVIVAL,
  chemistry: MASTER_CHEMISTRY,
  combat: MASTER_COMBAT,
};


  /** Flat lookup of every skill (branches + masters). */
  export const ALL_SKILLS: ProfessionSkill[] = (PROFESSIONS).flatMap(p => {
    const list: ProfessionSkill[] = PROFESSION_BRANCHES[p].flatMap(b => b.skills);
    const m = PROFESSION_MASTERS[p];
    if (m) list.push(m);
    return list;
  });

  const SKILL_BY_ID: Record<string, ProfessionSkill> = Object.fromEntries(
    ALL_SKILLS.map(s => [s.id, s]),
  );

  export function getSkill(id: string): ProfessionSkill | undefined {
    return SKILL_BY_ID[id];
  }

  // ─── Effect aggregation ─────────────────────────────────────────────────────

  /** Sum the numeric passive effects of every learned skill. */
  export function aggregatePassives(learned: Iterable<string>): ProfessionEffects {
    const out: ProfessionEffects = {};
    for (const id of learned) {
      const s = SKILL_BY_ID[id];
      if (!s) continue;
      for (const [k, v] of Object.entries(s.passive)) {
        out[k] = (out[k] ?? 0) + v;
      }
    }
    return out;
  }

  /** Returns true if any learned skill has the boolean flag set. */
  export function hasFlag(learned: Iterable<string>, flag: string): boolean {
    for (const id of learned) {
      const s = SKILL_BY_ID[id];
      if (s && s.extras[flag] === true) return true;
    }
    return false;
  }

  /** Collect the set of string-valued unlocks (e.g. all "harvesterUnlocked X"). */
  export function getUnlocks(learned: Iterable<string>, key: string): string[] {
    const out = new Set<string>();
    for (const id of learned) {
      const s = SKILL_BY_ID[id];
      const v = s?.extras[key];
      if (typeof v === 'string') out.add(v);
    }
    return [...out];
  }

  // ─── Persistence shape ──────────────────────────────────────────────────────

  export interface ProfessionState {
    /** XP earned per profession (only spent XP is removed). */
    xp: Partial<Record<Profession, number>>;
    /** Skill ids the player has learned (de-duplicated). */
    learned: string[];
  }

  export const EMPTY_PROFESSION_STATE: ProfessionState = { xp: {}, learned: [] };
  