import { WeaponStats, AbilityDef, SkillNode, PlayerStats } from './types';

export const WEAPONS: WeaponStats[] = [
  {
    id: 'iron_sword',
    name: 'Iron Sword',
    type: 'sword',
    damage: 25,
    speed: 1.2,
    range: 2.5,
    element: 'none',
    icon: '⚔️',
    color: 0xaaaaaa,
    description: 'A reliable one-handed sword. Balanced attack speed and damage.',
  },
  {
    id: 'fire_axe',
    name: 'Fire Axe',
    type: 'axe',
    damage: 40,
    speed: 0.7,
    range: 2.8,
    element: 'fire',
    icon: '🪓',
    color: 0xff4400,
    description: 'A heavy axe imbued with fire. Slow but devastating.',
  },
  {
    id: 'shadow_dagger',
    name: 'Shadow Dagger',
    type: 'dagger',
    damage: 15,
    speed: 2.0,
    range: 1.8,
    element: 'none',
    icon: '🗡️',
    color: 0x440066,
    description: 'Swift dual daggers. High attack speed, low damage.',
  },
  {
    id: 'thunder_mace',
    name: 'Thunder Mace',
    type: 'mace',
    damage: 35,
    speed: 0.9,
    range: 2.2,
    element: 'lightning',
    icon: '🔱',
    color: 0xffdd00,
    description: 'A crackling mace. Stuns enemies on hit.',
  },
  {
    id: 'iron_pistol',
    name: 'Iron Pistol',
    type: 'gun',
    damage: 30,
    speed: 1.5,
    range: 40,
    element: 'none',
    icon: '🔫',
    color: 0x888888,
    description: 'A reliable sidearm. Fires bullets at range.',
  },
  {
    id: 'hellfire_shotgun',
    name: 'Hellfire Shotgun',
    type: 'gun',
    damage: 60,
    speed: 0.6,
    range: 15,
    element: 'fire',
    icon: '🔫',
    color: 0xff4400,
    description: 'Brutal close-range spread. Destroys anything nearby.',
  },
];

export const ABILITIES: AbilityDef[] = [
  {
    id: 'whirlwind',
    name: 'Whirlwind',
    icon: '🌀',
    description: 'Spin attack hitting all nearby enemies.',
    manaCost: 20,
    cooldown: 5,
    damage: 40,
    unlocked: true,
    key: '1',
    color: '#4fc3f7',
  },
  {
    id: 'fireball',
    name: 'Fireball',
    icon: '🔥',
    description: 'Launch a blazing fireball at your target.',
    manaCost: 30,
    cooldown: 4,
    damage: 55,
    unlocked: false,
    key: '2',
    color: '#ff6b35',
  },
  {
    id: 'shield_bash',
    name: 'Shield Bash',
    icon: '🛡️',
    description: 'Slam your shield forward, stunning enemies.',
    manaCost: 15,
    cooldown: 3,
    damage: 20,
    unlocked: false,
    key: '3',
    color: '#69f0ae',
  },
  {
    id: 'berserker_rage',
    name: 'Berserker Rage',
    icon: '💢',
    description: 'Enter a rage state, doubling attack speed for 5 seconds.',
    manaCost: 40,
    cooldown: 12,
    damage: 0,
    unlocked: false,
    key: '4',
    color: '#ef5350',
  },
  {
    id: 'lightning_strike',
    name: 'Lightning Strike',
    icon: '⚡',
    description: 'Call down a lightning bolt on your target.',
    manaCost: 35,
    cooldown: 6,
    damage: 70,
    unlocked: false,
    key: '5',
    color: '#fff176',
  },
  {
    id: 'ice_spike',
    name: 'Ice Spike',
    icon: '🧊',
    description: 'Erupt a burst of ice shards that freeze and shatter enemies.',
    manaCost: 28,
    cooldown: 5,
    damage: 50,
    unlocked: false,
    key: '6',
    color: '#66ccff',
  },
];

export const SKILL_TREE: SkillNode[] = [
  // Strength branch
  { id: 'str1', name: 'Power Strike', description: '+5% melee damage per level', maxLevel: 3, currentLevel: 0, stat: 'strength', bonusPerLevel: 5, x: 0, y: 0 },
  { id: 'str2', name: 'Heavy Blow', description: '+10% chance to stagger per level', maxLevel: 3, currentLevel: 0, requires: ['str1'], stat: 'strength', bonusPerLevel: 10, x: 0, y: 1 },
  { id: 'str3', name: 'Titan Grip', description: '+8% weapon damage per level', maxLevel: 3, currentLevel: 0, requires: ['str2'], stat: 'strength', bonusPerLevel: 8, x: 0, y: 2 },
  // Ability: Whirlwind unlock
  { id: 'abil_whirlwind', name: 'Whirlwind', description: 'Unlocks Whirlwind spin attack', maxLevel: 1, currentLevel: 1, requires: ['str1'], stat: 'ability', abilityId: 'whirlwind', bonusPerLevel: 0, x: 1, y: 1 },
  // Agility branch
  { id: 'agi1', name: 'Swift Feet', description: '+5% movement speed per level', maxLevel: 3, currentLevel: 0, stat: 'agility', bonusPerLevel: 5, x: 2, y: 0 },
  { id: 'agi2', name: 'Dodge Roll', description: '+8% dodge chance per level', maxLevel: 3, currentLevel: 0, requires: ['agi1'], stat: 'agility', bonusPerLevel: 8, x: 2, y: 1 },
  { id: 'agi3', name: 'Blade Dance', description: '+10% attack speed per level', maxLevel: 3, currentLevel: 0, requires: ['agi2'], stat: 'agility', bonusPerLevel: 10, x: 2, y: 2 },
  // Intellect branch
  { id: 'int1', name: 'Arcane Mind', description: '+10 max mana per level', maxLevel: 3, currentLevel: 0, stat: 'intellect', bonusPerLevel: 10, x: 4, y: 0 },
  { id: 'int2', name: 'Spell Power', description: '+8% ability damage per level', maxLevel: 3, currentLevel: 0, requires: ['int1'], stat: 'intellect', bonusPerLevel: 8, x: 4, y: 1 },
  // Ability: Fireball
  { id: 'abil_fireball', name: 'Fireball', description: 'Unlocks Fireball spell', maxLevel: 1, currentLevel: 0, requires: ['int1'], stat: 'ability', abilityId: 'fireball', bonusPerLevel: 0, x: 5, y: 1 },
  { id: 'abil_lightning', name: 'Lightning Strike', description: 'Unlocks Lightning Strike', maxLevel: 1, currentLevel: 0, requires: ['int2'], stat: 'ability', abilityId: 'lightning_strike', bonusPerLevel: 0, x: 4, y: 2 },
  // Endurance branch
  { id: 'end1', name: 'Iron Skin', description: '+15 max health per level', maxLevel: 3, currentLevel: 0, stat: 'endurance', bonusPerLevel: 15, x: 6, y: 0 },
  { id: 'end2', name: 'Steadfast', description: '+5% damage reduction per level', maxLevel: 3, currentLevel: 0, requires: ['end1'], stat: 'endurance', bonusPerLevel: 5, x: 6, y: 1 },
  // Ability: Shield Bash
  { id: 'abil_shieldbash', name: 'Shield Bash', description: 'Unlocks Shield Bash', maxLevel: 1, currentLevel: 0, requires: ['end1'], stat: 'ability', abilityId: 'shield_bash', bonusPerLevel: 0, x: 7, y: 1 },
  // Ability: Berserker Rage
  { id: 'abil_berserker', name: 'Berserker Rage', description: 'Unlocks Berserker Rage', maxLevel: 1, currentLevel: 0, requires: ['str3', 'agi3'], stat: 'ability', abilityId: 'berserker_rage', bonusPerLevel: 0, x: 1, y: 3 },
];

export const INITIAL_PLAYER_STATS: PlayerStats = {
  health: 100,
  maxHealth: 100,
  mana: 80,
  maxMana: 80,
  stamina: 100,
  maxStamina: 100,
  // Legacy 8 Attributes — all start at 10
  strength: 10,
  vitality: 10,
  endurance: 10,
  intellect: 10,
  wisdom: 10,
  dexterity: 10,
  agility: 10,
  tactics: 10,
  level: 1,
  experience: 0,
  skillPoints: 3,
  // Survival vitals — start fed, hydrated, rested, normothermic
  hunger: 100,
  maxHunger: 100,
  thirst: 100,
  maxThirst: 100,
  temperature: 37,
  fatigue: 100,
  maxFatigue: 100,
  bleeding: false,
  infected: false,
};

export const CAMERA_MODES = {
  'first-person': { name: 'First Person', shortcut: 'V (cycle)' },
  'third-person': { name: 'Third Person', shortcut: 'V (cycle)' },
  'arpg': { name: 'ARPG View', shortcut: 'V (cycle)' },
} as const;

export const KEYBINDS = {
  MOVE_FORWARD: 'KeyW',
  MOVE_BACKWARD: 'KeyS',
  MOVE_LEFT: 'KeyA',
  MOVE_RIGHT: 'KeyD',
  JUMP: 'Space',
  ROLL: 'ShiftLeft',
  SWAP_WEAPON: 'KeyQ',
  CAMERA_CYCLE: 'KeyV',
  PAUSE: 'Escape',
  SKILL_TREE: 'KeyT',
  INVENTORY: 'KeyI',
  ABILITY_1: 'Digit1',
  ABILITY_2: 'Digit2',
  ABILITY_3: 'Digit3',
  ABILITY_4: 'Digit4',
  ABILITY_5: 'Digit5',
  HELP: 'KeyH',
  /** Generic interact key — open doors, talk to NPCs, enter buildings, etc.
      DoorSystem and InteriorPortalSystem both listen on this single code so
      one keypress drives door swing + interior enter/exit in lockstep. */
  INTERACT: 'KeyE',
  DEBUG_PANEL: 'Backquote',
  PERF_TOGGLE: 'F8',
};
