import { engineManifestSchema } from "./types";

/**
 * Armada era — naval/pirate titles (Flare Boss Arena, island crawlers).
 * Isometric ARPG camera, KayKit/bounty-rush animation libraries, FBA CDN pipeline.
 */
export const ARMADA_ENGINE_MANIFEST = engineManifestSchema.parse({
  version: 1,
  era: "armada",
  unit: "metres",
  updatedAt: "2026-07-09T00:00:00.000Z",
  controllers: [
    {
      id: "fba-isometric-hero",
      label: "Flare Boss Arena · Isometric Hero",
      driver: "legacy",
      worldScale: 1,
      targetHeightM: 2.1,
      gravity: -22,
      jumpHeight: 4,
      speed: 6,
      flySpeed: 10,
      acceleration: 18,
      deceleration: 18,
      headBoneName: "Head",
      rotateY: 0,
      animationLibraryId: "kaykit-bountyrush",
    },
    {
      id: "fba-pirate-npc",
      label: "KayKit Pirate NPC",
      driver: "legacy",
      worldScale: 1,
      targetHeightM: 1.95,
      gravity: -22,
      jumpHeight: 0,
      speed: 1.1,
      flySpeed: 0,
      acceleration: 8,
      deceleration: 12,
      headBoneName: "Head",
      rotateY: 0,
      animationLibraryId: "kaykit-pirate-embedded",
    },
  ],
  cameras: [
    {
      id: "fba-iso-fixed",
      label: "FBA Fixed Isometric",
      mode: "arpg",
      minDistance: 18,
      maxDistance: 18,
      lookAtHeightRatio: 0.55,
      shoulderOffset: 0,
      fov: 32,
      mouseSensitivity: 2,
      springCamera: false,
      springTime: 0,
    },
    {
      id: "fba-orbit-boss",
      label: "FBA Boss Orbit",
      mode: "orbit",
      minDistance: 12,
      maxDistance: 22,
      lookAtHeightRatio: 0.6,
      shoulderOffset: 0,
      fov: 45,
      mouseSensitivity: 3,
      springCamera: true,
      springTime: 0.1,
    },
  ],
  animationLibraries: [
    {
      id: "kaykit-bountyrush",
      label: "KayKit Bounty Rush Skins",
      rig: "custom",
      companionPacks: [],
      clipMap: {
        idle: "_idle_a",
        walk: "_run",
        attack: "_combo_a",
        dodge: "_dodge",
        hurt: "_damage",
      },
      clips: [
        { name: "idle", source: "_idle_a", loop: true },
        { name: "walk", source: "_run", loop: true },
        { name: "attack", source: "_combo_a", loop: false },
        { name: "dodge", source: "_dodge", loop: false },
      ],
    },
    {
      id: "kaykit-pirate-embedded",
      label: "KayKit Pirate Kit (embedded clips)",
      rig: "custom",
      companionPacks: [],
      clipMap: {
        Idle: "Idle",
        Walk: "Walk",
        Wave: "Wave",
        Sword: "Sword",
      },
      clips: [
        { name: "Idle", source: "Idle", loop: true },
        { name: "Walk", source: "Walk", loop: true },
        { name: "Wave", source: "Wave", loop: false },
      ],
    },
  ],
  textures: {
    default: { colorSpace: "srgb", anisotropy: true, wrap: "repeat" },
    terrain: { colorSpace: "srgb", anisotropy: true, repeat: 4, wrap: "repeat" },
    character: { colorSpace: "srgb", anisotropy: true, wrap: "clamp" },
  },
  pipeline: {
    cdnBase: "https://flare-boss-arena.vercel.app",
    importScripts: {
      character: "artifacts/grudge-game/scripts/process-character.mjs",
      map: "artifacts/grudge-game/scripts/process-map.mjs",
      inspect: "artifacts/grudge-game/scripts/inspect-character-rigs.mjs",
    },
    defaultCharacterHeightM: 2.1,
    enemyScaleMixamo: 1,
    enemyScaleGlbAutoFitMaxM: 3.5,
  },
  libraries: {
    grudgeControl: "grudge-control",
    threejs: "three",
    rapier: "@dimforge/rapier3d-compat",
    forge: "https://forge.grudge-studio.com",
    assetStudio: "/asset-studio/",
  },
  games: [
    {
      id: "flare-boss-arena",
      label: "Flare Boss Arena",
      route: "/game",
      deployUrl: "https://flare-boss-arena.vercel.app",
      package: "@workspace/grudge-game",
      modes: ["dungeon", "camp", "boss"],
      playLoop: [
        "choose-fighter",
        "party",
        "equipment",
        "skills",
        "island-rounds",
        "boss-arena",
      ],
    },
  ],
});