import { engineManifestSchema } from "./types";

/** Canonical Nexus-era engine manifest — shared by client, API, Forge, Dash. */
export const NEXUS_ENGINE_MANIFEST = engineManifestSchema.parse({
  version: 1,
  era: "nexus",
  unit: "metres",
  updatedAt: "2026-06-26T00:00:00.000Z",
  controllers: [
    {
      id: "grudge-control-tps",
      label: "Grudge Control · Third Person",
      driver: "grudge-control",
      worldScale: 0.01,
      targetHeightM: 1.8,
      gravity: -22,
      jumpHeight: 5.5,
      speed: 8,
      flySpeed: 14,
      acceleration: 18,
      deceleration: 18,
      headBoneName: "mixamorigHead",
      rotateY: Math.PI,
      animationLibraryId: "quaternius-ual",
    },
    {
      id: "legacy-fps",
      label: "Legacy PlayerController · First Person",
      driver: "legacy",
      worldScale: 1,
      targetHeightM: 1.8,
      gravity: -22,
      jumpHeight: 5.5,
      speed: 8,
      flySpeed: 14,
      acceleration: 18,
      deceleration: 18,
      headBoneName: "mixamorigHead",
      rotateY: Math.PI,
      animationLibraryId: "quaternius-ual",
    },
  ],
  cameras: [
    {
      id: "tps-shoulder",
      label: "Third Person Shoulder",
      mode: "third-person",
      minDistance: 2.8,
      maxDistance: 9,
      lookAtHeightRatio: 0.72,
      shoulderOffset: 0.35,
      fov: 60,
      mouseSensitivity: 4,
      springCamera: true,
      springTime: 0.08,
    },
    {
      id: "arpg-orbit",
      label: "ARPG Orbit",
      mode: "arpg",
      minDistance: 4,
      maxDistance: 14,
      lookAtHeightRatio: 0.65,
      shoulderOffset: 0,
      fov: 55,
      mouseSensitivity: 3,
      springCamera: true,
      springTime: 0.12,
    },
    {
      id: "fps",
      label: "First Person",
      mode: "first-person",
      minDistance: 0,
      maxDistance: 0,
      lookAtHeightRatio: 0.9,
      shoulderOffset: 0,
      fov: 75,
      mouseSensitivity: 2,
      springCamera: false,
      springTime: 0,
    },
  ],
  animationLibraries: [
    {
      id: "quaternius-ual",
      label: "Quaternius + UAL Companion",
      rig: "quaternius",
      companionPacks: [
        "/models/animations/UAL1_Standard.glb",
        "/models/animations/UAL2_Standard.glb",
      ],
      clipMap: {
        Idle: "Idle",
        Idle_Neutral: "Idle",
        Walk: "Walk",
        Run: "Run",
        Run_Left: "StrafeLeft",
        Run_Right: "StrafeRight",
        Roll: "Jump",
        Sword_Slash: "Attack",
        Punch_Left: "Attack",
        Death: "Death",
        HitRecieve: "Hit",
        HitRecieve_2: "Hit",
        Interact: "Interact",
        Wave: "Wave",
        Idle_Loop: "Idle",
        Walk_Loop: "Walk",
        Jog_Fwd_Loop: "Run",
        Sprint_Loop: "Sprint",
        Jump_Start: "Jump",
        Jump_Loop: "JumpLoop",
        Jump_Land: "JumpLand",
        A_TPose: "",
      },
      clips: [
        { name: "Idle", source: "Idle", loop: true },
        { name: "Walk", source: "Walk", loop: true },
        { name: "Run", source: "Run", loop: true },
        { name: "Attack", source: "Sword_Slash", loop: false },
        { name: "Jump", source: "Roll", loop: false },
        { name: "Death", source: "Death", loop: false },
      ],
    },
    {
      id: "mixamo-locomotion",
      label: "Mixamo Locomotion Pack",
      rig: "mixamo",
      companionPacks: ["/models/animations/"],
      clipMap: {},
      clips: [
        { name: "Idle", source: "idle.glb", loop: true },
        { name: "Walk", source: "walk.glb", loop: true },
        { name: "Run", source: "run.glb", loop: true },
      ],
    },
  ],
  textures: {
    default: { colorSpace: "srgb", anisotropy: true, wrap: "repeat" },
    terrain: { colorSpace: "srgb", anisotropy: true, repeat: 8, wrap: "repeat" },
    character: { colorSpace: "srgb", anisotropy: true, wrap: "clamp" },
  },
  pipeline: {
    cdnBase: "https://assets.grudge-studio.com/grudge-nexus",
    importScripts: {
      character: "artifacts/arpg-game/scripts/process-character.mjs",
      map: "artifacts/arpg-game/scripts/process-map.mjs",
      inspect: "artifacts/arpg-game/scripts/inspect-character-rigs.mjs",
    },
    defaultCharacterHeightM: 1.8,
    enemyScaleMixamo: 0.014,
    enemyScaleGlbAutoFitMaxM: 3,
  },
  libraries: {
    grudgeControl: "grudge-control",
    threejs: "three",
    rapier: "@dimforge/rapier3d-compat",
    forge: "https://forge.grudge-studio.com",
    assetStudio: "/asset-studio/",
  },
});